"""
Geometry Data Models

Foundational immutable dataclasses used throughout the
Auto Layout Engine.

Status:
    Implemented in LAYOUT-002

Dependencies:
    None

Used By:
    LAYOUT-003 through LAYOUT-014
"""

from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional, Tuple


@dataclass(frozen=True, slots=True)
class Footprint:
    """
    Physical geometry and keepout definition.

    Generated by FootprintGenerator.
    """

    node_id: str
    component_type: str
    width_mm: float
    height_mm: float
    keepout_mm: float
    polygon: Any
    keepout_polygon: Any
    rotation_deg: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class Obstacle:
    """
    Placement exclusion region.
    """

    obstacle_id: str
    polygon: Any
    obstacle_type: str
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class PlacementConstraint:
    """
    Placement requirements for a node.
    """

    node_id: str
    min_x_mm: Optional[float] = None
    max_x_mm: Optional[float] = None
    min_y_mm: Optional[float] = None
    max_y_mm: Optional[float] = None
    attach_to: Optional[str] = None
    preferred_region: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class ScoreBreakdown:
    """
    Layout quality metrics.
    """

    gate_passed: bool
    overlap_score: float
    spacing_score: float
    symmetry_score: float
    compactness_score: float
    edge_compliance_score: float
    aesthetics_score: float
    overall_score: float

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class LayoutCandidate:
    """
    Complete layout solution.
    """

    placements: Dict[str, Tuple[float, float]]
    score: ScoreBreakdown
    template_name: str
    generation_time_sec: float
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class Site:
    """
    Primary placement location.
    """

    site_id: str
    x_mm: float
    y_mm: float
    capacity: int = 1
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class Corridor:
    """
    Coupler placement region.
    """

    corridor_id: str
    start_site: str
    end_site: str
    center_x_mm: float
    center_y_mm: float
    width_mm: float
    length_mm: float
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class Shell:
    """
    Resonator allocation region.
    """

    shell_id: str
    parent_site: str
    radius_mm: float
    start_angle_deg: float
    end_angle_deg: float
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class Slot:
    """
    Launchpad location.
    """

    slot_id: str
    edge: str
    x_mm: float
    y_mm: float
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class Channel:
    """
    Feedline routing allocation.
    """

    channel_id: str
    start_x_mm: float
    start_y_mm: float
    end_x_mm: float
    end_y_mm: float
    width_mm: float
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class Floorplan:
    """
    Complete template floorplan.
    """

    sites: List[Site]
    corridors: List[Corridor]
    shells: List[Shell]
    slots: List[Slot]
    channels: List[Channel]
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
