"""Execution context model for tracking simulation pipeline state, timing, and artifacts."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from app.simulation.service.state_manager import PipelineState
from app.simulation.workspace import WorkspaceMetadata


class RollbackPolicy(str, Enum):
    """Policies for cleaning up or preserving workspaces upon completion or failure."""

    DELETE_ALL = "DELETE_ALL"
    KEEP_ALL = "KEEP_ALL"
    DELETE_ON_SUCCESS = "DELETE_ON_SUCCESS"  # Keep on failure (recommended default)


class ExecutionContext(BaseModel):
    """Pydantic v2 model representing the thread-safe context of a pipeline run.

    This context is passed through each phase of the simulation pipeline.
    """

    simulation_id: str = Field(
        ...,
        description="The unique UUID string associated with the simulation job."
    )
    workspace: Optional[WorkspaceMetadata] = Field(
        default=None,
        description="The metadata of the sandboxed workspace, if created."
    )
    status: PipelineState = Field(
        default=PipelineState.REQUEST_RECEIVED,
        description="The current state of the simulation pipeline."
    )
    current_phase: Optional[str] = Field(
        default=None,
        description="The name of the currently executing pipeline phase."
    )
    start_time: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the simulation request began execution."
    )
    end_time: Optional[datetime] = Field(
        default=None,
        description="Timestamp when the simulation completed, failed, or was cancelled."
    )
    execution_metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary solver settings, processor count, or binary versions."
    )
    generated_artifacts: List[str] = Field(
        default_factory=list,
        description="List of absolute paths to files generated by the pipeline."
    )
    artifacts_metadata: Dict[str, Dict[str, Any]] = Field(
        default_factory=dict,
        description="Detailed dictionary tracking file size, checksum, and creation time in real-time."
    )
    geometry_metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Captured GeometryMetadata model dictionary."
    )
    mesh_metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Captured MeshMetadata model dictionary."
    )
    config_metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Captured PalaceConfig metadata dictionary."
    )
    runner_metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Captured RunnerMetadata model dictionary."
    )
    timing: Dict[str, float] = Field(
        default_factory=dict,
        description="High-resolution phase execution durations in seconds."
    )
    warnings: List[str] = Field(
        default_factory=list,
        description="List of non-fatal warnings captured during execution."
    )
    errors: List[str] = Field(
        default_factory=list,
        description="List of error descriptions captured during execution."
    )
    rollback_policy: RollbackPolicy = Field(
        default=RollbackPolicy.DELETE_ON_SUCCESS,
        description="The strategy to apply for cleaning up workspace directories."
    )

    class Config:
        """Pydantic configuration."""
        arbitrary_types_allowed = True
