const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, 'src/components/documentation/sections');

const files = {
  'export-design.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Export a Design</h1>
      <p className="text-lg text-slate-600 mb-8">
        Once validation and simulations are complete, you must export your design into standard industry formats for physical fabrication or external simulation.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">GDSII (Graphic Data System)</h2>
      <p className="text-slate-600 mb-6">
        GDSII is the standard file format for communicating 2D integrated circuit layouts to a foundry. It contains binary representations of planar geometric shapes, text labels, and layer assignments.
      </p>

      <AlertBox type="warning" title="Negative vs Positive Masks">
        Foundries use different photolithography processes. If your foundry uses a "Positive Resist" process, you must export a <strong>Negative Mask</strong> (where polygons represent areas where metal is etched away). Verify this with your fabrication facility before generating the GDSII!
      </AlertBox>

      <h2 className="text-2xl font-bold mb-4 mt-10">OASIS Format</h2>
      <p className="text-slate-600 mb-6">
        For massive multi-qubit chips, GDSII files can exceed several gigabytes. Silicofeller supports exporting to the OASIS (Open Artwork System Interchange Standard) format, which offers up to 10x file size compression over GDSII without losing precision.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Exporting to External CAD</h2>
      <p className="text-slate-600 mb-6">
        If you need to perform thermal or mechanical stress analysis on your chip package, you can export the 3D volumetric representation to standard CAD formats:
      </p>
      <ul className="list-disc pl-6 space-y-3 text-slate-600 mb-8">
        <li><strong>STEP (.stp):</strong> Standardized 3D model format.</li>
        <li><strong>STL:</strong> Mesh format (not recommended for exact physics, but useful for 3D printing custom sample holders).</li>
      </ul>
    </div>
  );
}`,

  'qiskit-metal-code.tsx': `import React from "react";
import { CodeBlock } from "../CodeBlock";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Generated Qiskit Metal Code</h1>
      <p className="text-lg text-slate-600 mb-8">
        Silicofeller Quantum Studio is built on top of IBM's open-source Qiskit Metal framework. The entire visual schematic is backed by dynamically generated Python scripts.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Exporting the Script</h2>
      <p className="text-slate-600 mb-6">
        You can export the entire project as a standalone Python file (.py) or a Jupyter Notebook (.ipynb). This script can be run locally on any machine with Qiskit Metal installed, completely independent of the Silicofeller cloud.
      </p>

      <CodeBlock language="python" code={\`# Auto-generated by Silicofeller Quantum Studio
import qiskit_metal as metal
from qiskit_metal import designs, draw
from qiskit_metal.qlibrary.qubits.transmon_cross import TransmonCross

# 1. Initialize Design
design = designs.DesignPlanar()
design.overwrite_enabled = True

# 2. Setup Substrate
design.setup.drc.spacing_min = '5um'
design.setup.drc.trace_width = '10um'

# 3. Instantiate Components
Q1 = TransmonCross(design, 'Q1', options=dict(
    pos_x='0um', pos_y='0um',
    cross_width='30um', cross_length='200um',
    connection_pads=dict(
        readout=dict(connector_type='0', connector_location='90', trace_gap='4um')
    )
))

# 4. Rebuild UI
gui = metal.MetalGUI(design)
gui.rebuild()
gui.autoscale()
\`} />

      <AlertBox type="info" title="No Vendor Lock-in">
        Because the output is pure Qiskit Metal, you are never locked into the Silicofeller ecosystem. You own the code and can modify it locally using any standard IDE.
      </AlertBox>
    </div>
  );
}`,

  'design-summary.tsx': `import React from "react";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Design Summary Report</h1>
      <p className="text-lg text-slate-600 mb-8">
        The Design Summary provides a high-level bill of materials (BOM) and metric overview of your completed quantum processor.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Key Metrics Tracked</h2>
      <ul className="space-y-4 mb-8">
        <li className="bg-slate-50 p-5 rounded-lg border border-slate-200 shadow-sm">
          <strong className="text-slate-900 block mb-2 text-lg">Component Count</strong>
          <span className="text-slate-600">Total number of Qubits, Resonators, Feedlines, and Pads. Useful for verifying that the expected topology was instantiated correctly.</span>
        </li>
        <li className="bg-slate-50 p-5 rounded-lg border border-slate-200 shadow-sm">
          <strong className="text-slate-900 block mb-2 text-lg">Total Die Area</strong>
          <span className="text-slate-600">The physical bounding box of the layout. Crucial for ensuring the design fits within the reticle limits of the foundry's stepper machine (e.g., max 20mm x 20mm).</span>
        </li>
        <li className="bg-slate-50 p-5 rounded-lg border border-slate-200 shadow-sm">
          <strong className="text-slate-900 block mb-2 text-lg">Pin/Pad Count</strong>
          <span className="text-slate-600">The number of external wirebond connections required. This dictates what type of cryogenic sample holder and PCB you will need to purchase.</span>
        </li>
      </ul>

      <h2 className="text-2xl font-bold mb-4 mt-10">Export Formats</h2>
      <p className="text-slate-600 mb-6">
        The Summary Report can be exported as a PDF for management review, or as a JSON file for automated integration into inventory management systems.
      </p>
    </div>
  );
}`,

  'verification-report.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Verification Report</h1>
      <p className="text-lg text-slate-600 mb-8">
        The Verification Report is a cryptographic proof that the design passed all Four Domains of the DRC suite.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Compliance Certification</h2>
      <p className="text-slate-600 mb-6">
        Many external foundries require proof that a design has passed standard DRC checks before they will accept the GDSII file. If a broken file is submitted, it can crash their internal mask-generation software.
      </p>
      
      <p className="text-slate-600 mb-6">
        The Verification Report outputs a detailed log of every check performed, the thresholds used, and the timestamp of the pass.
      </p>

      <div className="bg-slate-900 text-emerald-400 p-4 rounded-xl font-mono text-sm mb-10 shadow-lg">
        [PASS] Graph Acyclic Verification<br/>
        [PASS] T-Junction Rule Check<br/>
        [PASS] Min Spacing (5um) DRC - 0 Violations<br/>
        [PASS] Frequency Collision Estimator (100MHz threshold)<br/>
        [WARN] Transmon_3 Anharmonicity (-150MHz) is below target.<br/>
        [PASS] Ground Plane Euler Characteristic: X=1 (No Islands)
      </div>

      <AlertBox type="info" title="Foundry Sign-off">
        Silicofeller Verification Reports include a cryptographic hash matching the exported GDSII file. Foundries partnered with Silicofeller can automatically verify this hash to fast-track your design into the fabrication queue.
      </AlertBox>
    </div>
  );
}`,

  'simulation-report.tsx': `import React from "react";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Simulation Report</h1>
      <p className="text-lg text-slate-600 mb-8">
        The Simulation Report consolidates the results of all computationally heavy LOM and Palace FEA tasks into a single, readable document.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Contents of the Report</h2>
      
      <ul className="list-disc pl-6 space-y-3 text-slate-600 mb-8">
        <li><strong>Hamiltonian Parameters:</strong> The final estimated $f_{01}$, $\\alpha$, and $E_C$ for every qubit on the chip.</li>
        <li><strong>Coupling Matrix (J):</strong> An $N \\times N$ matrix detailing the exact coupling strength (in MHz) between every pair of qubits and resonators.</li>
        <li><strong>Coherence Estimates:</strong> Predicted $T_1$ limits based on Energy Participation Ratio analysis of the dielectric interfaces.</li>
        <li><strong>Scattering Parameters:</strong> Embedded vector graphics of the S11 and S21 plots for all transmission lines.</li>
      </ul>

      <h2 className="text-2xl font-bold mb-4 mt-10">Cross-Referencing</h2>
      <p className="text-slate-600 mb-6">
        The report explicitly highlights any discrepancies between the <em>Target</em> frequencies defined in the Properties Inspector and the <em>Simulated</em> frequencies derived from the 3D physics extraction. If the delta is too large, you must iterate on the geometric design.
      </p>
    </div>
  );
}`,

  'tapeout-report.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Tapeout Report</h1>
      <p className="text-lg text-slate-600 mb-8">
        The Tapeout Report is the final, comprehensive dossier generated right before the chip is sent to the cleanroom. It merges the Design Summary, Verification Report, and Simulation Report into one master document.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Manufacturing Instructions</h2>
      <p className="text-slate-600 mb-6">
        Beyond just data, the Tapeout Report includes critical human-readable instructions for the fabrication technicians:
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-10">
        <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
          <h3 className="font-bold text-slate-900 mb-2">Layer Stackup</h3>
          <p className="text-sm text-slate-600">Clearly defines which GDSII layers correspond to which physical materials (e.g., Layer 1 = Niobium Base, Layer 2 = Aluminum Junctions, Layer 3 = Airbridges).</p>
        </div>
        <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
          <h3 className="font-bold text-slate-900 mb-2">Critical Dimensions (CD)</h3>
          <p className="text-sm text-slate-600">Lists the specific coordinates of the most sensitive features on the chip (usually the Josephson Junctions) so that SEM operators know exactly where to measure after lithography.</p>
        </div>
      </div>

      <AlertBox type="warning" title="Immutable State">
        Generating a Tapeout Report locks the current project revision. Any further changes to the schematic will force a new revision number to ensure the Tapeout Report strictly matches the exported GDSII file.
      </AlertBox>
    </div>
  );
}`,

  'tapeout-package.tsx': `import React from "react";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">The Tapeout Package (.zip)</h1>
      <p className="text-lg text-slate-600 mb-8">
        The ultimate deliverable of Silicofeller Quantum Studio is the Tapeout Package—a single ZIP archive containing everything the foundry needs to build your quantum chip.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Package Contents</h2>
      
      <ul className="space-y-4 mb-8">
        <li className="flex items-start gap-4 p-4 border border-slate-200 rounded-xl">
          <div className="bg-blue-100 text-blue-700 font-bold px-3 py-1 rounded">1</div>
          <div>
            <h3 className="font-bold text-slate-900">Mask Files</h3>
            <p className="text-slate-600 text-sm">The \`design.gds\` or \`design.oas\` files containing the 2D polygon layouts.</p>
          </div>
        </li>
        <li className="flex items-start gap-4 p-4 border border-slate-200 rounded-xl">
          <div className="bg-blue-100 text-blue-700 font-bold px-3 py-1 rounded">2</div>
          <div>
            <h3 className="font-bold text-slate-900">Documentation</h3>
            <p className="text-slate-600 text-sm">The PDF Tapeout Report, including layer definitions and critical dimension targets.</p>
          </div>
        </li>
        <li className="flex items-start gap-4 p-4 border border-slate-200 rounded-xl">
          <div className="bg-blue-100 text-blue-700 font-bold px-3 py-1 rounded">3</div>
          <div>
            <h3 className="font-bold text-slate-900">Source Code</h3>
            <p className="text-slate-600 text-sm">The \`qiskit_metal_export.py\` script used to generate the polygons, provided for reproducibility and auditing.</p>
          </div>
        </li>
        <li className="flex items-start gap-4 p-4 border border-slate-200 rounded-xl">
          <div className="bg-blue-100 text-blue-700 font-bold px-3 py-1 rounded">4</div>
          <div>
            <h3 className="font-bold text-slate-900">Digital Signatures</h3>
            <p className="text-slate-600 text-sm">A \`checksums.txt\` file containing SHA-256 hashes of all files in the archive to detect corruption during transfer.</p>
          </div>
        </li>
      </ul>

      <p className="text-slate-600 mt-8 italic">
        Once you download the Tapeout Package, email or securely transfer it to your fabrication partner. Your work in the software is done; now the physics takes over!
      </p>
    </div>
  );
}`,

  'qclang-overview.tsx': `import React from "react";
import { CodeBlock } from "../CodeBlock";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">QCLang Overview</h1>
      <p className="text-lg text-slate-600 mb-8">
        QCLang (Quantum Circuit Language) is Silicofeller's proprietary Domain Specific Language (DSL). It acts as the immutable source of truth bridging the Visual Schematic Editor and the backend physics compilers.
      </p>

      <div className="my-8 rounded-xl overflow-hidden border border-slate-200 shadow-sm">
        <img src="/brain/63033335-280b-4630-beb9-8bb527edd274/qclang_api_1782265202083.png" alt="API Integration" className="w-full h-auto object-cover" />
      </div>

      <h2 className="text-2xl font-bold mb-4 mt-10">Why a DSL?</h2>
      <p className="text-slate-600 mb-6">
        While Qiskit Metal is powerful, writing raw Python code to place 100 qubits is tedious and error-prone. QCLang is a declarative, JSON-like language optimized specifically for describing topological graphs and physical parametric components.
      </p>
      
      <p className="text-slate-600 mb-6">
        When you drag a component in the UI, the frontend modifies the QCLang Abstract Syntax Tree (AST). This AST is highly compressible, mathematically provable, and instantly translatable into Python, GDSII, or Gmsh formats.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Core Syntax Concepts</h2>
      <CodeBlock language="json" code={\`// QCLang is structured in blocks
project {
  name: "Falcon_V1"
  foundry: "MIT_LL"
}

// Global Variables
vars {
  gap_width = 5um
  substrate_eps = 11.45
}

// Component Instantiation
component TransmonCross as Q1 {
  pos_x: 0
  pos_y: 0
  cross_width: 30um
}
\`} />
    </div>
  );
}`,

  'examples-templates.tsx': `import React from "react";
import { CodeBlock } from "../CodeBlock";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">QCLang Examples & Templates</h1>
      <p className="text-lg text-slate-600 mb-8">
        To rapidly jumpstart a design without clicking through the UI, you can directly inject QCLang templates into the Code Editor panel.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Basic Qubit-Resonator Pair</h2>
      <p className="text-slate-600 mb-6">
        This template instantiates a single Transmon Cross and connects its readout pin to a Quarter-Wave resonator.
      </p>
      
      <CodeBlock language="json" code={\`component TransmonCross as Q1 {
  pos_x: 0mm
  pos_y: 0mm
  cross_length: 200um
}

component RouteMeander as Readout_1 {
  target_freq: 6.5 GHz
  pin_start: Q1.readout
  pin_end: Feedline.tie_in
  meander_spacing: 150um
}\`} />

      <h2 className="text-2xl font-bold mb-4 mt-10">Tunable Coupler Bus</h2>
      <p className="text-slate-600 mb-6">
        This demonstrates connecting two data qubits via an intermediary tunable bus for high-fidelity CZ gates.
      </p>
      
      <CodeBlock language="json" code={\`component TunableCoupler as TC_1 {
  pos_x: 1.5mm
  pos_y: 0mm
}

route Bus_A {
  pin_start: Q1.east
  pin_end: TC_1.west
}

route Bus_B {
  pin_start: TC_1.east
  pin_end: Q2.west
}\`} />
    </div>
  );
}`,

  'parse-qclang.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";
import { CodeBlock } from "../CodeBlock";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Parse QCLang</h1>
      <p className="text-lg text-slate-600 mb-8">
        Silicofeller provides a standalone Node.js and Python parser for interacting with QCLang files programmatically.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">The QCLang AST Compiler</h2>
      <p className="text-slate-600 mb-6">
        The compiler (written in Rust, wrapped in WebAssembly/Python) takes raw \`.qcl\` text and outputs a strict JSON AST. This is useful for writing custom linters or integrating with your own internal foundry scripts.
      </p>

      <CodeBlock language="javascript" code={\`import { parseQCLang } from '@silicofeller/qclang-parser';
import * as fs from 'fs';

const source = fs.readFileSync('my_chip.qcl', 'utf8');
try {
  const ast = parseQCLang(source);
  console.log("Found components:", ast.components.length);
} catch (error) {
  console.error("Syntax Error on line:", error.line);
}\`} />

      <AlertBox type="info" title="Strict Typing">
        The parser enforces strict unit typing. If you define a width as \`20GHz\`, the parser will immediately throw a Type Error before the AST is even generated. Lengths must be in \`m, mm, um, nm\` and frequencies in \`Hz, kHz, MHz, GHz\`.
      </AlertBox>
    </div>
  );
}`,

  'qclang-syntax.tsx': `import React from "react";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">QCLang Syntax Reference</h1>
      <p className="text-lg text-slate-600 mb-8">
        A comprehensive guide to the lexical rules and grammar of QCLang.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Variables and Mathematics</h2>
      <p className="text-slate-600 mb-6">
        Variables are defined in the \`vars {}\` block. You can perform standard arithmetic operations within parameter definitions.
      </p>
      <div className="bg-slate-900 text-slate-300 p-4 rounded-xl font-mono text-sm mb-10">
        vars &#123;<br/>
        &nbsp;&nbsp;base_freq = 5.0 GHz<br/>
        &nbsp;&nbsp;detuning = 150 MHz<br/>
        &#125;<br/>
        <br/>
        component Transmon as Q2 &#125;<br/>
        &nbsp;&nbsp;target_freq: base_freq + detuning<br/>
        &#125;
      </div>

      <h2 className="text-2xl font-bold mb-4 mt-10">Macros and Loops</h2>
      <p className="text-slate-600 mb-6">
        QCLang supports simple \`for\` loops to instantiate arrays of components rapidly.
      </p>
      <div className="bg-slate-900 text-slate-300 p-4 rounded-xl font-mono text-sm mb-10">
        for i in 1..5 &#123;<br/>
        &nbsp;&nbsp;component Transmon as Q_$&#123;i&#125; &#123;<br/>
        &nbsp;&nbsp;&nbsp;&nbsp;pos_x: i * 1.5mm<br/>
        &nbsp;&nbsp;&#125;<br/>
        &#125;
      </div>
    </div>
  );
}`,

  'build-from-source.tsx': `import React from "react";
import { CodeBlock } from "../CodeBlock";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Build the Client from Source</h1>
      <p className="text-lg text-slate-600 mb-8">
        For enterprise users needing strict security audits or custom proxy configurations, the Silicofeller Python Client can be built directly from the source code.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Prerequisites</h2>
      <ul className="list-disc pl-6 space-y-3 text-slate-600 mb-8">
        <li>Python 3.10+</li>
        <li>Rust Toolchain (cargo) for compiling the QCLang parser bindings.</li>
        <li>Git</li>
      </ul>

      <h2 className="text-2xl font-bold mb-4 mt-10">Compilation Steps</h2>
      <CodeBlock language="bash" code={\`# 1. Clone the repository
git clone https://github.com/silicofeller/silicofeller-client.git
cd silicofeller-client

# 2. Build the Rust extensions
python -m pip install setuptools-rust
python setup.py build_ext --inplace

# 3. Install in development mode
pip install -e .\`} />

      <AlertBox type="warning" title="Windows Users">
        If you are building on Windows, ensure you have the Visual Studio C++ Build Tools installed before compiling the Rust extensions, otherwise \`cargo\` will fail to link the binaries.
      </AlertBox>
    </div>
  );
}`,

  'api-reference.tsx': `import React from "react";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">API Reference</h1>
      <p className="text-lg text-slate-600 mb-8">
        The Silicofeller platform offers a comprehensive suite of APIs for programmatic control over the design, simulation, and deployment lifecycle.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
        <div className="bg-white border border-slate-200 p-6 rounded-xl shadow-sm text-center">
          <div className="w-16 h-16 mx-auto bg-blue-100 rounded-full flex items-center justify-center mb-4">
            <span className="text-blue-600 font-bold text-xl">Py</span>
          </div>
          <h3 className="font-bold text-slate-900 mb-2">Python SDK</h3>
          <p className="text-sm text-slate-600">The primary interface for quantum engineers. Automate topologies and run large-scale parameter sweeps.</p>
        </div>
        
        <div className="bg-white border border-slate-200 p-6 rounded-xl shadow-sm text-center">
          <div className="w-16 h-16 mx-auto bg-purple-100 rounded-full flex items-center justify-center mb-4">
            <span className="text-purple-600 font-bold text-xl">REST</span>
          </div>
          <h3 className="font-bold text-slate-900 mb-2">REST API</h3>
          <p className="text-sm text-slate-600">Standardized HTTP endpoints for CI/CD integration, user management, and triggering batch simulations.</p>
        </div>
        
        <div className="bg-white border border-slate-200 p-6 rounded-xl shadow-sm text-center">
          <div className="w-16 h-16 mx-auto bg-emerald-100 rounded-full flex items-center justify-center mb-4">
            <span className="text-emerald-600 font-bold text-xl">WS</span>
          </div>
          <h3 className="font-bold text-slate-900 mb-2">WebSockets</h3>
          <p className="text-sm text-slate-600">Real-time bi-directional streaming. Used for collaborative multi-user editing and live simulation progress bars.</p>
        </div>
      </div>
    </div>
  );
}`,

  'python-client.tsx': `import React from "react";
import { CodeBlock } from "../CodeBlock";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Python Client SDK</h1>
      <p className="text-lg text-slate-600 mb-8">
        The \`silicofeller\` Python package provides native objects for interacting with the cloud API, allowing you to manipulate QCLang graphs natively in Python.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Installation</h2>
      <CodeBlock language="bash" code="pip install silicofeller" />

      <h2 className="text-2xl font-bold mb-4 mt-10">Basic Authentication and Project Load</h2>
      <CodeBlock language="python" code={\`import silicofeller as sf

# Initialize client (uses SILICOFELLER_API_KEY environment variable)
client = sf.Client()

# Load a project from the cloud
project = client.get_project("proj_alpha_v2")

# Modify a parameter programmatically
q1 = project.get_component("Q1")
q1.set_property("cross_width", "32um")

# Save and run DRC
project.save()
results = project.run_drc()

if results.passed:
    print("Ready for fabrication!")
\`} />
    </div>
  );
}`,

  'rest-api.tsx': `import React from "react";
import { CodeBlock } from "../CodeBlock";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">REST API</h1>
      <p className="text-lg text-slate-600 mb-8">
        Base URL: \`https://api.silicofeller.com/v1/\`
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Core Endpoints</h2>
      
      <div className="space-y-6 mb-10">
        <div className="border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-50 border-b border-slate-200 px-4 py-3 flex gap-3 items-center">
            <span className="bg-blue-600 text-white font-mono text-xs px-2 py-1 rounded font-bold">GET</span>
            <span className="font-mono text-slate-900 font-bold">/projects/&#123;id&#125;/export</span>
          </div>
          <div className="p-4 bg-white text-sm text-slate-600">
            Triggers an export task. Requires a query parameter \`format=gdsii|qiskit|qclang\`. Returns a task ID.
          </div>
        </div>

        <div className="border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-50 border-b border-slate-200 px-4 py-3 flex gap-3 items-center">
            <span className="bg-emerald-600 text-white font-mono text-xs px-2 py-1 rounded font-bold">POST</span>
            <span className="font-mono text-slate-900 font-bold">/simulations/run</span>
          </div>
          <div className="p-4 bg-white text-sm text-slate-600">
            Submit a new Palace FEA or LOM simulation to the cluster queue.
          </div>
        </div>
      </div>

      <h2 className="text-2xl font-bold mb-4 mt-10">Rate Limiting</h2>
      <p className="text-slate-600 mb-6">
        Standard API keys are limited to 100 requests per minute. Batch simulation triggering is limited to 5 concurrent tasks per organization tier.
      </p>
    </div>
  );
}`,

  'websocket-events.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">WebSocket Events</h1>
      <p className="text-lg text-slate-600 mb-8">
        For real-time UI updates and collaborative editing, Silicofeller streams JSON payloads over WebSockets.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Connection Protocol</h2>
      <p className="text-slate-600 mb-6">
        Connect via \`wss://ws.silicofeller.com/stream\`. Authentication is handled via a Bearer token in the connection headers.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Common Event Payloads</h2>
      <div className="bg-slate-900 text-emerald-400 p-4 rounded-xl font-mono text-sm mb-10 shadow-lg">
        // Received when a collaborator moves a component<br/>
        &#123;<br/>
        &nbsp;&nbsp;"type": "GRAPH_MUTATION",<br/>
        &nbsp;&nbsp;"component_id": "Q1",<br/>
        &nbsp;&nbsp;"mutation": &#123;<br/>
        &nbsp;&nbsp;&nbsp;&nbsp;"pos_x": "1200um"<br/>
        &nbsp;&nbsp;&#125;,<br/>
        &nbsp;&nbsp;"user_id": "usr_992x"<br/>
        &#125;
      </div>

      <AlertBox type="info" title="Simulation Progress">
        You can subscribe to the \`SIMULATION_TICK\` event to stream real-time meshing and solving progress logs directly from the AWS Palace cluster to your custom dashboard.
      </AlertBox>
    </div>
  );
}`,

  'authentication.tsx': `import React from "react";
import { CodeBlock } from "../CodeBlock";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Authentication</h1>
      <p className="text-lg text-slate-600 mb-8">
        All programmatic access to Silicofeller Quantum Studio is secured via API Keys (Bearer Tokens).
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Generating an API Key</h2>
      <ol className="list-decimal pl-6 space-y-4 text-slate-600 mb-10">
        <li>Log into the Silicofeller Dashboard.</li>
        <li>Navigate to <strong>Account Settings &gt; Developer API</strong>.</li>
        <li>Click <strong>Generate New Token</strong>.</li>
        <li>Assign a scope (e.g., \`read-only\` or \`full-access\`).</li>
        <li>Copy the token. It will only be displayed once.</li>
      </ol>

      <AlertBox type="warning" title="Security Best Practices">
        Never hardcode your API key into scripts or commit it to GitHub. Always use environment variables or a secure secret manager (like AWS Secrets Manager or HashiCorp Vault).
      </AlertBox>

      <h2 className="text-2xl font-bold mb-4 mt-10">Using the Token</h2>
      <p className="text-slate-600 mb-6">
        Pass the token in the \`Authorization\` header of your HTTP requests.
      </p>
      <CodeBlock language="bash" code="Authorization: Bearer sf_live_xxxxxxxxxxxxxxxxxxxxxx" />
    </div>
  );
}`
};

Object.keys(files).forEach(file => {
  fs.writeFileSync(path.join(dir, file), files[file], 'utf8');
});
console.log('Batch 4 expanded');
