const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, 'src/components/documentation/sections');

const files = {
  'fabrication-drc.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Four-Domain DRC: Fabrication</h1>
      <p className="text-lg text-slate-600 mb-8">
        Fabrication DRC ensures that the geometric polygons generated by your layout can actually be manufactured using standard photolithography and e-beam processes at your target foundry.
      </p>

      <div className="my-8 rounded-xl overflow-hidden border border-slate-200 shadow-sm">
        <img src="/brain/63033335-280b-4630-beb9-8bb527edd274/validation_drc_1782265191432.png" alt="Fabrication Checks" className="w-full h-auto object-cover" />
      </div>

      <h2 className="text-2xl font-bold mb-4 mt-10">Lithography Constraints</h2>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-10">
        <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
          <h3 className="font-bold text-slate-900 mb-2">1. Minimum Trace Width</h3>
          <p className="text-sm text-slate-600">Standard 193nm DUV steppers cannot reliably print features smaller than 1µm. If you request a CPW trace width of 0.5µm, you are forcing the foundry to use slow, expensive E-beam lithography for the entire base layer. The engine flags traces below the photolithography limit.</p>
        </div>
        <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
          <h3 className="font-bold text-slate-900 mb-2">2. Acute Angle (Acid Trap)</h3>
          <p className="text-sm text-slate-600">Polygon vertices with internal angles &lt; 45° act as "acid traps" during wet etching, where chemical etchant pools and over-etches the surrounding metal. The DRC engine flags any acute angles in meandering resonators.</p>
        </div>
        <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
          <h3 className="font-bold text-slate-900 mb-2">3. Minimum Area</h3>
          <p className="text-sm text-slate-600">Tiny isolated islands of metal ("dust") can flake off during lift-off processes and short out adjacent structures. Polygons smaller than 2µm² are flagged.</p>
        </div>
        <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
          <h3 className="font-bold text-slate-900 mb-2">4. Chip Boundary Clearance</h3>
          <p className="text-sm text-slate-600">Features cannot be placed closer than 50µm to the dicing streets. The mechanical dicing saw causes micro-fractures that will destroy any nearby quantum coherence.</p>
        </div>
      </div>

      <AlertBox type="warning" title="Foundry Variability">
        Every foundry (e.g., MIT Lincoln Labs, Rigetti Foundry Services) has a unique rule deck. Ensure you select the correct Foundry Profile in your Project Settings so the Fabrication DRC applies the correct limitations.
      </AlertBox>
    </div>
  );
}`,

  'connectivity-drc.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Four-Domain DRC: Connectivity & Ground</h1>
      <p className="text-lg text-slate-600 mb-8">
        The final phase of the DRC suite validates the macroscopic electrical integrity of the entire chip mask, focusing heavily on ground plane continuity.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Ground Plane Topology</h2>
      <p className="text-slate-600 mb-6">
        Superconducting chips rely on an infinite ground plane. Every time you draw a CPW line, you etch away a gap, carving a "moat" into the ground plane.
      </p>

      <p className="text-slate-600 mb-6">
        If you route your lines in a closed loop (e.g., surrounding a qubit completely with feedlines), you create a <strong>Ground Island</strong>. This is a piece of metal that is physically disconnected from the main ground plane.
      </p>

      <div className="bg-rose-50 border-l-4 border-rose-500 p-4 mb-8 rounded-r-xl">
        <h3 className="text-rose-800 font-bold mb-1">The Danger of Ground Islands</h3>
        <p className="text-rose-700 text-sm">Isolated ground patches have undefined electrical potential. They will act as parasitic resonators with spurious modes that aggressively couple to and destroy nearby qubits. The DRC engine computes the topological Euler characteristic of the ground plane to mathematically guarantee zero islands exist.</p>
      </div>

      <h2 className="text-2xl font-bold mb-4 mt-10">Wirebond Accessibility</h2>
      <p className="text-slate-600 mb-6">
        The final check ensures that all defined Launch Pads (the points where off-chip cables connect) are located on the outer perimeter of the chip boundary.
      </p>
      <AlertBox type="info" title="Packaging Limits">
        If a launch pad is placed in the center of the chip, the physical wirebonder cannot reach it without the bonding wire crossing over (and shorting to) the rest of the chip.
      </AlertBox>
    </div>
  );
}`,

  'severity-levels.tsx': `import React from "react";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Understand Severity Levels</h1>
      <p className="text-lg text-slate-600 mb-8">
        Silicofeller categorizes DRC and validation errors into four distinct severity levels to help you prioritize fixes during the layout phase.
      </p>

      <div className="space-y-6 mb-10">
        <div className="flex items-start gap-4 p-5 border border-slate-200 rounded-xl shadow-sm">
          <div className="w-5 h-5 mt-1 rounded-full bg-slate-400 flex-shrink-0"></div>
          <div>
            <h3 className="font-bold text-slate-900 text-lg">Level 0: Information</h3>
            <p className="text-slate-600 mt-2">These are best practice suggestions. For example, advising that a trace width is non-standard but technically manufacturable. Level 0 does not block simulation or GDSII export.</p>
          </div>
        </div>
        
        <div className="flex items-start gap-4 p-5 border border-amber-200 bg-amber-50 rounded-xl shadow-sm">
          <div className="w-5 h-5 mt-1 rounded-full bg-amber-500 flex-shrink-0 animate-pulse"></div>
          <div>
            <h3 className="font-bold text-amber-900 text-lg">Level 1: Warning</h3>
            <p className="text-amber-800 mt-2">Potential physics issues, such as slight frequency detuning or suboptimal Purcell filter bandwidth. The platform allows you to export the design, but forces you to acknowledge the warning first.</p>
          </div>
        </div>
        
        <div className="flex items-start gap-4 p-5 border border-orange-200 bg-orange-50 rounded-xl shadow-sm">
          <div className="w-5 h-5 mt-1 rounded-full bg-orange-500 flex-shrink-0"></div>
          <div>
            <h3 className="font-bold text-orange-900 text-lg">Level 2: Violation</h3>
            <p className="text-orange-800 mt-2">Definite physical rule breaks. Examples include overlapping geometries, shorted components, or photolithography limits breached. <strong>Blocks export to GDSII and blocks Palace FEA simulations.</strong></p>
          </div>
        </div>
        
        <div className="flex items-start gap-4 p-5 border border-rose-200 bg-rose-50 rounded-xl shadow-sm">
          <div className="w-5 h-5 mt-1 rounded-full bg-rose-600 flex-shrink-0"></div>
          <div>
            <h3 className="font-bold text-rose-900 text-lg">Level 3: Fatal</h3>
            <p className="text-rose-800 mt-2">The Abstract Syntax Tree is logically corrupted. This occurs if a component references a deleted net, or if the JSON graph contains cyclic redundancies. The rendering pipeline halts immediately.</p>
          </div>
        </div>
      </div>
    </div>
  );
}`,

  'target-frequencies.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Target Frequencies</h1>
      <p className="text-lg text-slate-600 mb-8">
        Assigning exact target frequencies is the most critical physics parameter when designing a multi-qubit chip. It dictates your gate times, coherence limits, and cryogenic hardware requirements.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Standard Operating Bands</h2>
      <p className="text-slate-600 mb-6">
        The microwave spectrum must be carefully partitioned.
      </p>

      <div className="overflow-x-auto mb-8 border border-slate-200 rounded-xl shadow-sm">
        <table className="w-full text-left text-sm">
          <thead className="bg-slate-50 border-b border-slate-200">
            <tr>
              <th className="px-6 py-4 font-semibold text-slate-900">Component</th>
              <th className="px-6 py-4 font-semibold text-slate-900">Typical Frequency Band</th>
              <th className="px-6 py-4 font-semibold text-slate-900">Reasoning</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 bg-white">
            <tr className="hover:bg-slate-50 transition-colors">
              <td className="px-6 py-4 font-medium text-slate-900">Transmons ($f_{01}$)</td>
              <td className="px-6 py-4">4.0 GHz — 5.5 GHz</td>
              <td className="px-6 py-4 text-slate-600">Below 4 GHz, thermal noise at 15mK dominates. Above 5.5 GHz, you risk colliding with readout bands.</td>
            </tr>
            <tr className="hover:bg-slate-50 transition-colors">
              <td className="px-6 py-4 font-medium text-slate-900">Readout Resonators</td>
              <td className="px-6 py-4">6.0 GHz — 8.0 GHz</td>
              <td className="px-6 py-4 text-slate-600">Must be highly detuned from qubits to enable dispersive shift readout without Purcell decay.</td>
            </tr>
            <tr className="hover:bg-slate-50 transition-colors">
              <td className="px-6 py-4 font-medium text-slate-900">Purcell Filters</td>
              <td className="px-6 py-4">Matches Resonator</td>
              <td className="px-6 py-4 text-slate-600">Acts as a bandpass filter centered on the resonator's readout tone.</td>
            </tr>
          </tbody>
        </table>
      </div>

      <AlertBox type="info" title="Iterative Simulation Requirement">
        The analytical frequencies provided in the UI are rough estimates based on standard capacitance models. Because geometric fringing fields affect the final capacitance matrix ($C_{max}$), the true $f_{01}$ frequencies must be verified using the Energy Participation Ratio (EPR) method in the Physics Analysis simulation tab.
      </AlertBox>
    </div>
  );
}`,

  'frequency-collisions.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Frequency Collisions</h1>
      <p className="text-lg text-slate-600 mb-8">
        Avoiding frequency collisions is the absolute hardest part of fixed-frequency transmon design. A single collision can render an entire sub-lattice of the chip useless for quantum algorithms.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">The Three Collision Typologies</h2>
      
      <div className="space-y-6 mb-10">
        <div className="bg-white border border-slate-200 p-6 rounded-xl shadow-sm">
          <h3 className="font-bold text-slate-900 text-lg mb-2">Type 1: Fundamental Collision</h3>
          <p className="font-mono text-sm text-indigo-600 bg-indigo-50 inline-block px-2 py-1 rounded mb-3">|f_Q1 - f_Q2| &lt; 10 MHz</p>
          <p className="text-slate-600">Two directly neighboring qubits have nearly identical frequencies. The static $ZZ$ interaction dominates, meaning you cannot apply a single-qubit gate to $Q_1$ without also severely rotating $Q_2$.</p>
        </div>

        <div className="bg-white border border-slate-200 p-6 rounded-xl shadow-sm">
          <h3 className="font-bold text-slate-900 text-lg mb-2">Type 2: Cross-Resonance Spectator</h3>
          <p className="font-mono text-sm text-indigo-600 bg-indigo-50 inline-block px-2 py-1 rounded mb-3">|f_Q1 - f_Q3| &lt; 15 MHz</p>
          <p className="text-slate-600">Occurs when $Q_1$ and $Q_3$ share a common neighbor $Q_2$. When driving $Q_2$ at $Q_1$'s frequency to perform a Cross-Resonance gate, you accidentally drive $Q_3$ as well, causing severe "spectator" errors.</p>
        </div>

        <div className="bg-white border border-slate-200 p-6 rounded-xl shadow-sm">
          <h3 className="font-bold text-slate-900 text-lg mb-2">Type 3: Anharmonicity Collision</h3>
          <p className="font-mono text-sm text-indigo-600 bg-indigo-50 inline-block px-2 py-1 rounded mb-3">f_Q1 ≈ f_Q2 + α_Q2</p>
          <p className="text-slate-600">The 0→1 transition of $Q_1$ exactly matches the 1→2 transition of its neighbor $Q_2$. Driving $Q_1$ will cause $Q_2$ to leak out of the computational basis into the $|2\\rangle$ state, permanently destroying the quantum information.</p>
        </div>
      </div>

      <AlertBox type="tip" title="Post-Fabrication Tuning">
        If you manufacture a chip and discover a Type 1 collision due to lithography variations, you can use post-fabrication Laser Annealing to selectively heat the Josephson Junction. This shifts the junction resistance, permanently lowering the qubit's frequency by 50-100 MHz to resolve the collision.
      </AlertBox>
    </div>
  );
}`,

  'resonator-planning.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Resonator Multiplexing</h1>
      <p className="text-lg text-slate-600 mb-8">
        Cryogenic wiring is a massive physical bottleneck. To reduce the number of coaxial cables going down into the dilution refrigerator, multiple readout resonators are multiplexed onto a single feedline.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Frequency Domain Multiplexing (FDM)</h2>
      <p className="text-slate-600 mb-6">
        By assigning slightly different resonant lengths to 4-6 resonators, they can all couple to the same CPW feedline. You send a broadband microwave pulse containing all 6 frequencies down the line, and the reflected signal is digitized and demultiplexed via Fast Fourier Transform (FFT) at room temperature.
      </p>

      <div className="overflow-hidden rounded-xl border border-slate-200 mb-10 shadow-sm">
        <table className="w-full text-left text-sm">
          <thead className="bg-slate-50 border-b border-slate-200">
            <tr>
              <th className="px-6 py-4 text-slate-900 font-bold">Multiplex Group</th>
              <th className="px-6 py-4 text-slate-900 font-bold">Resonator Q1</th>
              <th className="px-6 py-4 text-slate-900 font-bold">Resonator Q2</th>
              <th className="px-6 py-4 text-slate-900 font-bold">Resonator Q3</th>
              <th className="px-6 py-4 text-slate-900 font-bold">DRC Status</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 bg-white">
            <tr className="hover:bg-slate-50">
              <td className="px-6 py-4 font-mono font-bold text-slate-700">Line A</td>
              <td className="px-6 py-4">6.12 GHz</td>
              <td className="px-6 py-4">6.25 GHz</td>
              <td className="px-6 py-4">6.38 GHz</td>
              <td className="px-6 py-4 text-emerald-600 font-bold">Passed (Optimal)</td>
            </tr>
            <tr className="hover:bg-slate-50">
              <td className="px-6 py-4 font-mono font-bold text-slate-700">Line B</td>
              <td className="px-6 py-4">7.05 GHz</td>
              <td className="px-6 py-4 text-rose-600 font-bold">7.08 GHz</td>
              <td className="px-6 py-4 text-rose-600 font-bold">7.11 GHz</td>
              <td className="px-6 py-4 text-rose-600 font-bold">Failed: Purcell Overlap</td>
            </tr>
          </tbody>
        </table>
      </div>

      <AlertBox type="warning" title="Bandwidth Requirements">
        Ensure at least 50 MHz separation between resonators on the same feedline. If they are closer, the "tails" of their Lorentzian line shapes will overlap, making it impossible for the room-temperature ADC to distinguish which qubit was measured.
      </AlertBox>
    </div>
  );
}`,

  'transmon-properties.tsx': `import React from "react";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Transmon Properties</h1>
      <p className="text-lg text-slate-600 mb-8">
        Understanding the core physical properties governing Transmon behavior is essential for predicting gate fidelities and coherence limits.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Coherence Times ($T_1$ and $T_2$)</h2>
      <p className="text-slate-600 mb-6">
        $T_1$ (Relaxation Time) is how long the qubit takes to decay from $|1\\rangle$ to $|0\\rangle$. $T_2$ (Dephasing Time) is how long the qubit maintains its quantum phase.
      </p>

      <div className="bg-slate-50 p-8 rounded-xl border border-slate-200 font-serif text-lg text-center mb-10 shadow-inner">
        <p className="mb-4">{"1/T_1 = Σ (p_i * tan(δ_i)) / ω_01"}</p>
        <p>{"1/T_2* = 1/(2*T_1) + 1/T_φ"}</p>
      </div>

      <p className="text-slate-600 mb-6">
        Where $p_i$ is the participation ratio of dielectric region $i$, and $\\tan(\\delta_i)$ is its loss tangent. These equations show that to increase $T_1$, you must minimize the electric field's interaction with lossy materials.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Capacitance and Charging Energy ($E_C$)</h2>
      <p className="text-slate-600 mb-6">
        The charging energy $E_C$ is the energy required to add a single Cooper pair to the transmon island. It is purely determined by the total shunt capacitance ($C_{\\Sigma}$) extracted from the geometry.
      </p>
      <div className="bg-slate-900 text-slate-300 p-4 rounded-xl font-mono text-sm text-center">
        E_C = e² / (2 * C_Σ)
      </div>
    </div>
  );
}`,

  'coherence-analysis.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";
import { CodeBlock } from "../CodeBlock";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Coherence Analysis (EPR)</h1>
      <p className="text-lg text-slate-600 mb-8">
        The Energy Participation Ratio (EPR) analysis quantifies exactly how much of the quantum zero-point energy is stored in dissipative (lossy) elements.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Dielectric Participation</h2>
      <p className="text-slate-600 mb-6">
        In superconducting circuits, most Two-Level System (TLS) loss does not occur in the bulk silicon or the bulk metal. It occurs at the microscopic oxidized interfaces:
      </p>
      
      <ul className="list-disc pl-6 space-y-3 text-slate-600 mb-8">
        <li><strong>Substrate-Air (SA):</strong> The surface of the silicon wafer.</li>
        <li><strong>Metal-Air (MA):</strong> The top surface of the Niobium trace.</li>
        <li><strong>Metal-Substrate (MS):</strong> The interface where the metal meets the silicon.</li>
      </ul>

      <AlertBox type="tip" title="Optimization Strategy">
        To increase $T_1$, you must push the electric field out of these interfaces and deeper into the low-loss bulk substrate. Increasing the gap spacing between the transmon pads forces the E-field lines to travel deeper through the silicon, reducing SA and MS participation ratios.
      </AlertBox>

      <h2 className="text-2xl font-bold mb-4 mt-10">Running EPR via API</h2>
      <p className="text-slate-600 mb-6">
        You can extract the participation matrix computationally by triggering a Palace FEA simulation and parsing the resulting json output.
      </p>
      
      <CodeBlock language="python" code={\`from silicofeller.simulations import EPRAnalysis

analysis = EPRAnalysis(project_id="Falcon_V1")
results = analysis.run(mesh_refinement=3)

print(f"Substrate Participation: {results.p_substrate}")
print(f"Predicted T1 Limit: {results.t1_limit_us} us")\`} />
    </div>
  );
}`,

  'anharmonicity.tsx': `import React from "react";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Anharmonicity (α)</h1>
      <p className="text-lg text-slate-600 mb-8">
        Anharmonicity determines the "speed limit" of your qubit. It dictates how fast you can apply microwave drive pulses without accidentally exciting the qubit into non-computational states.
      </p>

      <div className="bg-slate-900 text-white p-8 rounded-xl text-center mb-10 shadow-lg">
        <h3 className="text-indigo-300 font-bold mb-2">Fundamental Equation</h3>
        <p className="text-2xl font-serif tracking-widest">{"α = f_12 - f_01 ≈ -E_C"}</p>
      </div>

      <h2 className="text-2xl font-bold mb-4 mt-10">The Transmon Compromise</h2>
      <p className="text-slate-600 mb-6">
        A perfect harmonic oscillator (like an LC circuit) has perfectly equally spaced energy levels. You cannot use it as a qubit because driving the $0 \\rightarrow 1$ transition would simultaneously drive $1 \\rightarrow 2$, $2 \\rightarrow 3$, etc.
      </p>
      <p className="text-slate-600 mb-6">
        The Josephson Junction introduces non-linearity, making the $1 \\rightarrow 2$ transition slightly lower in frequency than the $0 \\rightarrow 1$ transition. This difference is $\\alpha$.
      </p>

      <ul className="list-disc pl-6 space-y-3 text-slate-600 mb-8">
        <li>In standard transmons, $\\alpha$ is strictly negative and roughly equal to the charging energy $-E_C$.</li>
        <li>Typical values range from <strong>-300 MHz to -200 MHz</strong>.</li>
        <li>If you attempt to apply a microwave pulse shorter than $\\sim 20$ ns, the frequency bandwidth of the pulse becomes wide enough to overcome $\\alpha$, causing leakage into the $|2\\rangle$ state.</li>
      </ul>
    </div>
  );
}`,

  'gate-fidelity.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Gate Fidelity Predictions</h1>
      <p className="text-lg text-slate-600 mb-8">
        Once the Hamiltonian parameters ($f_{01}$, $\\alpha$, $J_{ij}$) are extracted from the layout, Silicofeller can simulate the expected fidelity of single-qubit and two-qubit operations.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Cross-Resonance (CR) Gate Errors</h2>
      <p className="text-slate-600 mb-6">
        The primary 2-qubit gate for fixed-frequency transmons is the Cross-Resonance gate. It is driven by applying a microwave tone to the Control Qubit at the frequency of the Target Qubit.
      </p>

      <AlertBox type="warning" title="CR Limitations">
        CR gates require a strong static coupling ($J$) to be fast, but suffer from unwanted $ZX$ interactions if the detuning $\\Delta$ between the qubits is too small. The fidelity simulator calculates the effective CR drive strength and projects the coherent gate error based on your layout's exact $J/\\Delta$ ratio.
      </AlertBox>

      <h2 className="text-2xl font-bold mb-4 mt-10">Single Qubit (SQ) DRAG Pulses</h2>
      <p className="text-slate-600 mb-6">
        For single qubit gates, the simulator calculates the optimal DRAG (Derivative Removal by Adiabatic Gate) coefficient needed to suppress leakage into the $|2\\rangle$ state, providing a baseline error rate governed primarily by the calculated $T_1$ and $T_2$ coherence limits.
      </p>
    </div>
  );
}`,

  'create-simulation.tsx': `import React from "react";
import { CodeBlock } from "../CodeBlock";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Create a Simulation Task</h1>
      <p className="text-lg text-slate-600 mb-8">
        Solving Maxwell's equations for large quantum chips requires immense computational power. Heavy physics simulations are entirely decoupled from the frontend and offloaded to our scalable cloud compute cluster.
      </p>

      <div className="my-8 rounded-xl overflow-hidden border border-slate-200 shadow-sm">
        <img src="/brain/63033335-280b-4630-beb9-8bb527edd274/system_architecture_1782265216047.png" alt="Simulation Architecture" className="w-full h-auto object-cover" />
      </div>

      <h2 className="text-2xl font-bold mb-4 mt-10">Submission via the UI</h2>
      <p className="text-slate-600 mb-6">
        Click the <strong>"Simulate"</strong> button in the top toolbar. You can select either the fast <strong>LOM Solver</strong> (for capacitance matrix extraction) or the highly rigorous <strong>Palace FEA</strong> (for full wave electromagnetics).
      </p>

      <AlertBox type="info" title="Asynchronous Processing">
        Simulations can take anywhere from 5 minutes to 48 hours depending on mesh resolution. The UI will provide a persistent progress bar. You can close your browser; you will receive an email notification when the results are written to the database.
      </AlertBox>

      <h2 className="text-2xl font-bold mb-4 mt-10">API Submission</h2>
      <p className="text-slate-600 mb-6">
        For CI/CD pipelines, you can trigger simulations programmatically.
      </p>
      
      <CodeBlock language="bash" code={\`curl -X POST https://api.silicofeller.com/v1/simulations \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -d '{
    "project_id": "proj_99xx",
    "solver": "LOM",
    "mesh_resolution": "fine",
    "notify_email": "engineer@company.com"
  }'\`} />
    </div>
  );
}`,

  'run-analytical.tsx': `import React from "react";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Lumped Oscillator Model (LOM)</h1>
      <p className="text-lg text-slate-600 mb-8">
        The LOM solver is your workhorse for iterative design. It is much faster than full-wave FEA and provides highly accurate estimates for frequencies and coupling strengths.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">How LOM Works</h2>
      <p className="text-slate-600 mb-6">
        Instead of solving the full electromagnetic wave equations, LOM treats the chip as an abstract circuit of capacitors and inductors.
      </p>
      
      <div className="bg-slate-50 border border-slate-200 rounded-xl p-6 overflow-x-auto mb-10">
        <pre className="text-sm font-mono text-slate-800">
{\`graph TD
    A[GDSII Layout Polygons] --> B[Electrostatic Q3D Extractor]
    B -->|Solves Poisson Eq| C[Maxwell Capacitance Matrix C_max]
    C --> D[LOM Quantization Engine]
    D -->|Applies Josephson Inductances| E[f_01, E_C, g_ij]
    style C fill:#dbeafe,stroke:#3b82f6
    style E fill:#d1fae5,stroke:#10b981\`}
        </pre>
      </div>

      <p className="text-slate-600 mb-6">
        By extracting only the Maxwell Capacitance Matrix ($C_{max}$), LOM reduces a 10-hour simulation down to ~2 minutes, allowing you to rapidly tweak pad sizes until you hit your target frequencies.
      </p>
    </div>
  );
}`,

  'palace-adapter.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">AWS Palace FEA Adapter</h1>
      <p className="text-lg text-slate-600 mb-8">
        Silicofeller integrates natively with <strong>Palace</strong>, an open-source, massively parallel finite element solver for computational electromagnetics developed by AWS.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Why Palace?</h2>
      <p className="text-slate-600 mb-6">
        Commercial solvers like Ansys HFSS are incredibly expensive and notoriously difficult to scale across multiple cloud nodes. Palace is built on MFEM and runs natively on HPC clusters via MPI, allowing us to simulate massive 100+ qubit chips by distributing the mesh across dozens of EC2 instances simultaneously.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Automated Configuration</h2>
      <p className="text-slate-600 mb-6">
        You do not need to manually write Palace configuration files. When triggering a simulation, the Silicofeller backend automatically translates your QCLang AST and material selections into the required palace_config.json and generates the volumetric Gmsh files.
      </p>

      <AlertBox type="warning" title="Mesh Quality">
        The accuracy of Palace depends entirely on the quality of the volumetric mesh. If you experience simulation divergence, go back to the Export settings and increase the <strong>Mesh Refinement Level</strong> near the Josephson Junctions.
      </AlertBox>
    </div>
  );
}`,

  'review-simulation.tsx': `import React from "react";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Review Simulation Results</h1>
      <p className="text-lg text-slate-600 mb-8">
        Once your Palace or LOM simulation completes, navigate to the Reports tab to view the extracted physics parameters and interactive charts.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">S-Parameter Interpretation</h2>
      <p className="text-slate-600 mb-6">
        For feedlines and readout resonators, you should analyze the S21 magnitude plots. 
      </p>
      
      <ul className="list-disc pl-6 space-y-3 text-slate-600 mb-8">
        <li><strong>Resonance Dips:</strong> A sharp dip in the S21 transmission plot indicates the exact resonant frequency of the $\\lambda/4$ resonator.</li>
        <li><strong>Spurious Box Modes:</strong> If you see unexpected ripples or broad absorption bands in the S-parameter plot, it means your chip size has created an electromagnetic cavity resonance. You must add wirebond "vias" across your ground planes to push these box modes to higher, harmless frequencies.</li>
      </ul>

      <AlertBox type="tip" title="Data Export">
        All generated charts are backed by raw Touchstone (.s2p, .sNp) and CSV files. You can download these from the attachments panel for further analysis in MATLAB or Python.
      </AlertBox>
    </div>
  );
}`
};

Object.keys(files).forEach(file => {
  fs.writeFileSync(path.join(dir, file), files[file], 'utf8');
});
console.log('Batch 3 expanded');
