"""
QChipLang Code Generator
Emits Qiskit Metal Python, GDS netlist stubs, SPICE netlist, and JSON IR
from a validated AST.
"""

import json
import math
import textwrap
from datetime import datetime
from typing import Any, Dict, List, Optional

from .ast_nodes import *


class CodegenError(Exception):
    pass


# ─── Qiskit Metal Python Backend ─────────────────────────────────────────────

class QiskitMetalBackend:
    """
    Generates a Qiskit Metal Python script from the AST.

    Key design decisions:
      - Uses qiskit_metal.qlibrary components (TransmonPocket, CPWWaveguide, etc.)
      - For tile arrays > 100 qubits, uses nested Python loops over tile geometry
      - All coordinates in 'um' (Qiskit Metal default)
      - Generates a complete runnable script with design_options dicts
    """

    COMPONENT_MAP = {
        'transmon': 'TransmonPocket',
        'xmon': 'TransmonCross',
        'fluxonium': 'TransmonPocket',  # closest available
        'gatemon': 'TransmonPocket',
    }

    RESONATOR_MAP = {
        'quarter_wave': 'OpenToGroundCPW',
        'half_wave': 'RoutePathfinder',
        'lumped': 'CapNInterdigitated',
    }

    def __init__(self, prog: Program):
        self.prog = prog
        self.indent = 0
        self.lines: List[str] = []

    def _w(self, line: str = ''):
        self.lines.append('    ' * self.indent + line)

    def _section(self, title: str):
        self._w()
        self._w(f"# {'─' * 60}")
        self._w(f"# {title}")
        self._w(f"# {'─' * 60}")

    def _qv(self, v: Any) -> str:
        """Format a QValue for Qiskit Metal (string with unit)."""
        if isinstance(v, QValue):
            return f"'{v.number}{v.unit or ''}'"
        if isinstance(v, str):
            return f"'{v}'"
        if isinstance(v, bool):
            return str(v)
        if isinstance(v, (int, float)):
            return str(v)
        if isinstance(v, QArray):
            return '[' + ', '.join(self._qv(i) for i in v.items) + ']'
        if isinstance(v, QTuple):
            return '(' + ', '.join(self._qv(i) for i in v.items) + ')'
        return repr(v)

    def generate(self) -> str:
        self._emit_header()
        self._emit_imports()
        self._emit_design_init()
        self._emit_chip_meta()
        self._emit_qubits()
        self._emit_resonators()
        self._emit_couplers()
        self._emit_connections()
        self._emit_tile_arrays()
        self._emit_feedlines()
        self._emit_control_lines()
        self._emit_design_rules()
        self._emit_render_and_export()
        return '\n'.join(self.lines)

    def _emit_header(self):
        chip_name = self.prog.chip.name if self.prog.chip else 'QuantumChip'
        self._w(f'"""')
        self._w(f'QChipLang → Qiskit Metal')
        self._w(f'Generated: {datetime.now().isoformat(timespec="seconds")}')
        self._w(f'Chip: {chip_name}')
        if self.prog.chip:
            n = self.prog.chip.attrs.get('qubit_count')
            if n:
                self._w(f'Qubits: {self._qv(n)}')
        self._w(f'')
        self._w(f'This file was automatically generated by QChipLang v1.0.')
        self._w(f'Do not edit manually — regenerate from the .qcl source.')
        self._w(f'"""')

    def _emit_imports(self):
        self._section("Imports")
        self._w('import numpy as np')
        self._w('from qiskit_metal import designs, draw, MetalGUI')
        self._w('from qiskit_metal.qlibrary.qubits.transmon_pocket import TransmonPocket')
        self._w('from qiskit_metal.qlibrary.qubits.transmon_cross import TransmonCross')
        self._w('from qiskit_metal.qlibrary.tlines.meandered_line import RouteMeander')
        self._w('from qiskit_metal.qlibrary.tlines.pathfinder import RoutePathfinder')
        self._w('from qiskit_metal.qlibrary.tlines.straight_path import RouteStraight')
        self._w('from qiskit_metal.qlibrary.couplers.cap_n_xmon import CapNXmon')
        self._w('from qiskit_metal.qlibrary.terminations.open_to_ground import OpenToGround')
        self._w('from qiskit_metal.renderers.renderer_gds.gds_renderer import QGDSRenderer')
        self._w('from qiskit_metal.analyses.quantization import LOManalysis, EPRanalysis')

    def _emit_design_init(self):
        self._section("Design Initialization")
        self._w('# Initialize the design canvas')
        self._w("design = designs.DesignPlanar()")
        self._w("design.overwrite_enabled = True")
        self._w("# gui = MetalGUI(design)  # Uncomment for interactive GUI")
        self._w()

        # Chip dimensions
        if self.prog.chip:
            self._w("# Set chip dimensions from chip{} declaration")
            chip = self.prog.chip
            qubit_count = chip.attrs.get('qubit_count')
            if isinstance(qubit_count, QValue):
                n = int(qubit_count.number)
                side_mm = math.ceil(math.sqrt(n * 0.001) * 10) / 10  # ~1mm²/1000 qubits
                self._w(f"design.chips.main.size.size_x = '{side_mm * 1.5}mm'")
                self._w(f"design.chips.main.size.size_y = '{side_mm}mm'")
            self._w(f"design.chips.main.size.center_x = '0mm'")
            self._w(f"design.chips.main.size.center_y = '0mm'")

    def _emit_chip_meta(self):
        if not self.prog.chip:
            return
        self._section("Chip Metadata")
        chip = self.prog.chip
        self._w(f"# Chip: {chip.name}")
        for k, v in chip.attrs.items():
            self._w(f"#   {k}: {v}")

    def _emit_qubits(self):
        if not self.prog.qubits:
            return
        self._section("Qubit Placement")

        for q in self.prog.qubits:
            component = self.COMPONENT_MAP.get(
                str(q.attrs.get('type', 'transmon')), 'TransmonPocket'
            )

            if q.dims:
                # Array qubit — generate nested loop
                nx = q.dims[0]
                ny = q.dims[1] if len(q.dims) > 1 else 1
                spacing = q.attrs.get('spacing', QTuple([QValue(1000, 'um'), QValue(1000, 'um')]))
                origin = q.attrs.get('origin', QTuple([QValue(0, 'um'), QValue(0, 'um')]))

                sx = spacing.items[0] if isinstance(spacing, QTuple) else QValue(1000, 'um')
                sy = spacing.items[1] if isinstance(spacing, QTuple) and len(spacing.items) > 1 else sx
                ox = origin.items[0] if isinstance(origin, QTuple) else QValue(0, 'um')
                oy = origin.items[1] if isinstance(origin, QTuple) and len(origin.items) > 1 else QValue(0, 'um')

                self._w(f"# Qubit array '{q.name}' [{nx}x{ny}] = {nx*ny} qubits")
                self._w(f"_q_{q.name}_origin = ({ox.number}, {oy.number})  # um")
                self._w(f"_q_{q.name}_spacing = ({sx.number}, {sy.number})  # um")
                self._w(f"for _qix in range({nx}):")
                self.indent += 1
                self._w(f"for _qiy in range({ny}):")
                self.indent += 1
                self._w(f"_qname = f'{q.name}_{{_qix}}_{{_qiy}}'")
                self._w(f"_qx = _q_{q.name}_origin[0] + _qix * _q_{q.name}_spacing[0]")
                self._w(f"_qy = _q_{q.name}_origin[1] + _qiy * _q_{q.name}_spacing[1]")
                self._w(f"_q_opts = dict(")
                self.indent += 1

                # Frequency sweep
                freq = q.attrs.get('frequency')
                if isinstance(freq, QSweep):
                    self._w(f"# frequency: sweep({freq.start}, {freq.end}, {freq.mode})")
                    self._w(f"# Applied via alternating pattern — set in Hamiltonian extraction")
                else:
                    pad_width = q.attrs.get('pad_width', QValue(400, 'um'))
                    pad_height = q.attrs.get('pad_height', QValue(90, 'um'))
                    pad_gap = q.attrs.get('pad_gap', QValue(30, 'um'))
                    self._w(f"pad_width='{self._qv(pad_width)[1:-1]}',")
                    self._w(f"pad_height='{self._qv(pad_height)[1:-1]}',")
                    self._w(f"pad_gap='{self._qv(pad_gap)[1:-1]}',")

                self._w(f"pos_x=f'{{_qx}}um', pos_y=f'{{_qy}}um',")
                self.indent -= 1
                self._w(f")")
                self._w(f"{component}(design, _qname, options=_q_opts)")
                self.indent -= 2

            else:
                # Scalar qubit
                self._w(f"# Qubit '{q.name}'")
                pos = q.attrs.get('position', QTuple([QValue(0, 'um'), QValue(0, 'um')]))
                x = pos.items[0] if isinstance(pos, QTuple) else QValue(0, 'um')
                y = pos.items[1] if isinstance(pos, QTuple) and len(pos.items) > 1 else QValue(0, 'um')

                opts = {
                    'pos_x': f"'{x.number}um'",
                    'pos_y': f"'{y.number}um'",
                }
                pad_width = q.attrs.get('pad_width', QValue(400, 'um'))
                pad_height = q.attrs.get('pad_height', QValue(90, 'um'))
                pad_gap = q.attrs.get('pad_gap', QValue(30, 'um'))
                opts['pad_width'] = self._qv(pad_width)
                opts['pad_height'] = self._qv(pad_height)
                opts['pad_gap'] = self._qv(pad_gap)

                opt_str = ', '.join(f'{k}={v}' for k, v in opts.items())
                self._w(f"{component}(design, '{q.name}', options=dict({opt_str}))")
            self._w()

    def _emit_resonators(self):
        if not self.prog.resonators:
            return
        self._section("Readout Resonators")
        for r in self.prog.resonators:
            rtype = str(r.attrs.get('type', 'quarter_wave'))
            couples_to = r.attrs.get('couples_to', 'q0')
            coupling_gap = r.attrs.get('coupling_gap', QValue(10, 'um'))
            meander_w = r.attrs.get('meander_width', QValue(10, 'um'))
            meander_g = r.attrs.get('meander_gap', QValue(6, 'um'))

            self._w(f"# Resonator '{r.name}' ({rtype}), couples to '{couples_to}'")
            self._w(f"RouteMeander(design, '{r.name}', options=dict(")
            self.indent += 1
            self._w(f"pin_inputs=dict(")
            self.indent += 1
            self._w(f"start_pin=dict(component='{couples_to}', pin='readout'),")
            self._w(f"end_pin=dict(component='{r.name}_term', pin='open'),")
            self.indent -= 1
            self._w(f"),")
            self._w(f"meander=dict(spacing='200um', asymmetry='0um'),")
            self._w(f"lead=dict(start_straight='{self._qv(coupling_gap)[1:-1]}', end_straight='50um'),")
            self._w(f"fillet='99.9um',")
            self.indent -= 1
            self._w(f"))")
            self._w(f"OpenToGround(design, '{r.name}_term', options=dict(")
            self._w(f"    pos_x='0um', pos_y='0um', orientation='0'))")
            self._w()

    def _emit_couplers(self):
        if not self.prog.couplers:
            return
        self._section("Couplers")
        for c in self.prog.couplers:
            ctype = str(c.attrs.get('type', 'fixed'))
            connects = c.attrs.get('connects')
            refs = []
            if isinstance(connects, QArray):
                refs = [str(i) for i in connects.items if isinstance(i, str)]

            self._w(f"# Coupler '{c.name}' ({ctype})")
            if refs and len(refs) >= 2:
                self._w(f"CapNXmon(design, '{c.name}', options=dict(")
                self.indent += 1
                self._w(f"pin_inputs=dict(")
                self.indent += 1
                self._w(f"start_pin=dict(component='{refs[0]}', pin='bus_bot'),")
                self._w(f"end_pin=dict(component='{refs[1]}', pin='bus_top'),")
                self.indent -= 1
                self._w(f"),")
                coupling = c.attrs.get('coupling_strength')
                if coupling:
                    self._w(f"# coupling_strength: {coupling}")
                self.indent -= 1
                self._w(f"))")
            self._w()

    def _emit_connections(self):
        if not self.prog.connections:
            return
        self._section("Explicit Connections")
        for conn in self.prog.connections:
            ctype = conn.attrs.get('type', 'capacitive')
            strength = conn.attrs.get('strength')
            self._w(f"# connect {conn.left} -- {conn.right}  ({ctype}, {strength})")
            self._w(f"RoutePathfinder(design, 'conn_{conn.left}_{conn.right}', options=dict(")
            self.indent += 1
            self._w(f"pin_inputs=dict(")
            self.indent += 1
            self._w(f"start_pin=dict(component='{conn.left}', pin='bus_bot'),")
            self._w(f"end_pin=dict(component='{conn.right}', pin='bus_top'),")
            self.indent -= 1
            self._w(f"),")
            self.indent -= 1
            self._w(f"))")
            self._w()

    def _emit_tile_arrays(self):
        if not self.prog.tile_arrays:
            return
        self._section("Tile Arrays (Large-Scale)")
        for ta in self.prog.tile_arrays:
            count = ta.attrs.get('count')
            pitch = ta.attrs.get('pitch')
            tile_ref = ta.attrs.get('tile', 'UnknownTile')
            stitch = ta.attrs.get('stitch_edges', True)

            nx, ny = 1, 1
            if isinstance(count, QArray) and len(count.items) >= 2:
                nx = int(count.items[0].number)
                ny = int(count.items[1].number)

            px_um, py_um = 2050, 2050
            if isinstance(pitch, QTuple) and len(pitch.items) >= 2:
                px_um = pitch.items[0].number
                py_um = pitch.items[1].number

            total = nx * ny
            self._w(f"# Tile array '{ta.name}': {nx}×{ny} = {total:,} tiles of '{tile_ref}'")
            self._w(f"# Total qubits in this array: ~{total * 4:,} (assuming 4 qubits/tile)")
            self._w(f"# Pitch: {px_um}um × {py_um}um")
            self._w(f"_tile_nx, _tile_ny = {nx}, {ny}")
            self._w(f"_tile_px, _tile_py = {px_um}, {py_um}  # um")
            self._w(f"_ta_components = {{}}")
            self._w(f"for _ti in range(_tile_nx):")
            self.indent += 1
            self._w(f"for _tj in range(_tile_ny):")
            self.indent += 1
            self._w(f"_tname = f'{ta.name}_tile_{{_ti}}_{{_tj}}'")
            self._w(f"_tx = _ti * _tile_px")
            self._w(f"_ty = _tj * _tile_py")
            self._w(f"# Instantiate {tile_ref} tile at (_tx, _ty)um")
            self._w(f"# Each tile contains 4 qubits, 4 resonators, 4 couplers")
            self._w(f"for _qi in range(4):  # 4 qubits per tile")
            self.indent += 1
            self._w(f"_qoff_x = [0, 1, 0, 1][_qi] * 900  # um within tile")
            self._w(f"_qoff_y = [0, 0, 1, 1][_qi] * 900")
            self._w(f"_qfname = f'{{_tname}}_q{{_qi}}'")
            self._w(f"_qopts = dict(")
            self.indent += 1
            self._w(f"pos_x=f'{{_tx + _qoff_x}}um',")
            self._w(f"pos_y=f'{{_ty + _qoff_y}}um',")
            self._w(f"pad_width='400um', pad_height='90um', pad_gap='30um',")
            self._w(f"orientation=str(90 * _qi),")
            self.indent -= 1
            self._w(f")")
            self._w(f"TransmonPocket(design, _qfname, options=_qopts)")
            self._w(f"_ta_components[_qfname] = (_tx + _qoff_x, _ty + _qoff_y)")
            self.indent -= 1

            if stitch:
                self._w(f"# Stitch inter-tile connections")
                self._w(f"if _ti > 0:  # Connect to left neighbor tile")
                self.indent += 1
                self._w(f"_left_tile = f'{ta.name}_tile_{{_ti-1}}_{{_tj}}'")
                self._w(f"# Add west-east coupler (auto-generated)")
                self.indent -= 1

            self.indent -= 2
            self._w()

    def _emit_feedlines(self):
        if not self.prog.feedlines:
            return
        self._section("Feedlines (Readout)")
        for fl in self.prog.feedlines:
            self._w(f"# Feedline '{fl.name}'")
            self._w(f"RouteStraight(design, '{fl.name}', options=dict(")
            self.indent += 1
            self._w(f"total_length='10mm',")
            w = fl.attrs.get('width', QValue(10, 'um'))
            g = fl.attrs.get('gap', QValue(6, 'um'))
            self._w(f"trace_width='{self._qv(w)[1:-1]}', trace_gap='{self._qv(g)[1:-1]}',")
            self._w(f"# connects: {fl.attrs.get('connects', 'all resonators in row')}")
            self.indent -= 1
            self._w(f"))")
            self._w()

    def _emit_control_lines(self):
        for fl in self.prog.flux_lines:
            self._w(f"# Flux line '{fl.name}' — tunable coupler bias")
            self._w(f"# Targets: {fl.attrs.get('targets', 'tunable couplers')}")
            self._w(f"# mutual_inductance: {fl.attrs.get('mutual_inductance', '2pH')}")
            self._w()

        for dl in self.prog.drive_lines:
            self._w(f"# Drive line '{dl.name}' — multiplexed XY control")
            mux = dl.attrs.get('mux_count', 10)
            self._w(f"# Frequency-multiplexed: {mux} qubits per line")
            self._w()

    def _emit_design_rules(self):
        if not self.prog.design_rules:
            return
        self._section("Design Rule Parameters (for DRC scripts)")
        self._w("DESIGN_RULES = {")
        self.indent += 1
        for k, v in self.prog.design_rules.attrs.items():
            self._w(f"'{k}': {self._qv(v)},")
        self.indent -= 1
        self._w("}")

    def _emit_render_and_export(self):
        self._section("Render & Export")
        self._w("# Rebuild all components")
        self._w("design.rebuild()")
        self._w()
        self._w("# Export to GDS (requires gdspy)")
        self._w("gds = QGDSRenderer(design)")
        self._w("gds.options.path_filename = './output_chip.gds'")
        self._w("gds.export_to_gds()")
        self._w()
        self._w("# Export design options to JSON (for toolchain integration)")
        self._w("import json")
        self._w("with open('./design_options.json', 'w') as f:")
        self._w("    json.dump(design.components._design_options, f, indent=2, default=str)")
        self._w()
        self._w("print('QChipLang export complete.')")
        self._w("print(f'Components: {len(design.components)}')")
        self._w("print(f'GDS: ./output_chip.gds')")


# ─── JSON IR Backend ──────────────────────────────────────────────────────────

class JSONIRBackend:
    """Emits a JSON intermediate representation of the entire design."""

    def __init__(self, prog: Program):
        self.prog = prog

    def _serialize(self, v: Any) -> Any:
        if isinstance(v, QValue):
            return {'value': v.number, 'unit': v.unit}
        if isinstance(v, QArray):
            return [self._serialize(i) for i in v.items]
        if isinstance(v, QTuple):
            return {'tuple': [self._serialize(i) for i in v.items]}
        if isinstance(v, QSweep):
            return {'sweep': {'start': self._serialize(v.start), 'end': self._serialize(v.end), 'mode': v.mode}}
        if isinstance(v, QFromFile):
            return {'from_file': v.path}
        if isinstance(v, QRange):
            return {'range': [v.start, v.end]}
        if isinstance(v, dict):
            return {k: self._serialize(vv) for k, vv in v.items()}
        return v

    def _block(self, obj: Any) -> Dict:
        if hasattr(obj, 'attrs'):
            return self._serialize(obj.attrs)
        return {}

    def generate(self) -> str:
        chip = self.prog.chip
        ir = {
            'qchiplang_version': '1.0',
            'generated': datetime.now().isoformat(),
            'chip': {'name': chip.name, **self._serialize(chip.attrs)} if chip else None,
            'qubits': [{'name': q.name, 'dims': q.dims, **self._block(q)} for q in self.prog.qubits],
            'resonators': [{'name': r.name, **self._block(r)} for r in self.prog.resonators],
            'couplers': [{'name': c.name, **self._block(c)} for c in self.prog.couplers],
            'connections': [{'left': c.left, 'right': c.right, **self._block(c)} for c in self.prog.connections],
            'topologies': [{'name': t.name, **self._block(t)} for t in self.prog.topologies],
            'tiles': [{'name': t.name, **self._block(t)} for t in self.prog.tiles],
            'tile_arrays': [{'name': ta.name, **self._block(ta)} for ta in self.prog.tile_arrays],
            'feedlines': [{'name': f.name, **self._block(f)} for f in self.prog.feedlines],
            'design_rules': self._block(self.prog.design_rules) if self.prog.design_rules else None,
            'applications': [{'name': a.name, **self._block(a)} for a in self.prog.applications],
        }
        return json.dumps(ir, indent=2)


# ─── SPICE Netlist Backend ────────────────────────────────────────────────────

class SPICEBackend:
    """
    Generates a lumped-element SPICE netlist approximation.
    Each transmon qubit → LC oscillator with Josephson junction.
    Each resonator → series RLC.
    Each coupler → capacitor between qubit nodes.
    """

    def __init__(self, prog: Program):
        self.prog = prog
        self.lines: List[str] = []
        self._node = 0

    def _n(self) -> str:
        self._node += 1
        return f"N{self._node:04d}"

    def generate(self) -> str:
        chip = self.prog.chip
        self.lines.append(f"* QChipLang → SPICE Netlist")
        self.lines.append(f"* Generated: {datetime.now().isoformat()}")
        self.lines.append(f"* Chip: {chip.name if chip else 'Unknown'}")
        self.lines.append(f".SUBCKT QuantumChip")
        self.lines.append("")

        qubit_nodes: Dict[str, str] = {}

        for q in self.prog.qubits:
            if q.dims:
                nx = q.dims[0]
                ny = q.dims[1] if len(q.dims) > 1 else 1
                self.lines.append(f"* Array qubit {q.name} [{nx}x{ny}]")
                for i in range(min(nx * ny, 10)):  # Sample first 10 for netlist
                    node = self._n()
                    qubit_nodes[f"{q.name}_{i}"] = node
                    ec = q.attrs.get('Ec', QValue(0.25, 'GHz'))
                    ej = q.attrs.get('Ej', QValue(15.0, 'GHz'))
                    ec_val = ec.number if isinstance(ec, QValue) else 0.25
                    ej_val = ej.number if isinstance(ej, QValue) else 15.0
                    c_val = 1 / (8 * ec_val * 1e9) * 1e15  # fF
                    self.lines.append(f"* Qubit {q.name}_{i}: Ec={ec_val}GHz, Ej={ej_val}GHz")
                    self.lines.append(f"CJ_{q.name}_{i} {node} 0 {c_val:.2f}fF")
                    self.lines.append(f"BJ_{q.name}_{i} {node} 0 I='-{ej_val:.2f}n*sin(V({node}))'  $ Josephson element")
                if nx * ny > 10:
                    self.lines.append(f"* ... {nx*ny - 10} more qubits omitted for brevity")
            else:
                node = self._n()
                qubit_nodes[q.name] = node
                ec = q.attrs.get('Ec', QValue(0.25, 'GHz'))
                ej = q.attrs.get('Ej', QValue(15.0, 'GHz'))
                ec_val = ec.number if isinstance(ec, QValue) else 0.25
                ej_val = ej.number if isinstance(ej, QValue) else 15.0
                c_val = 1 / (8 * ec_val * 1e9) * 1e15
                self.lines.append(f"* Qubit {q.name}")
                self.lines.append(f"CJ_{q.name} {node} 0 {c_val:.2f}fF")
                self.lines.append(f"BJ_{q.name} {node} 0 I='-{ej_val:.2f}n*sin(V({node}))'")
            self.lines.append("")

        for r in self.prog.resonators:
            n1, n2 = self._n(), self._n()
            freq = r.attrs.get('frequency', QValue(6.8, 'GHz'))
            f = freq.number if isinstance(freq, QValue) else 6.8
            l_nh = 1 / ((2 * math.pi * f * 1e9) ** 2 * 1e-12) * 1e9
            self.lines.append(f"* Resonator {r.name} @ {f}GHz")
            self.lines.append(f"L_{r.name} {n1} {n2} {l_nh:.3f}nH")
            self.lines.append(f"C_{r.name} {n2} 0 1.0pF")
            self.lines.append("")

        for c in self.prog.couplers:
            connects = c.attrs.get('connects')
            coupling = c.attrs.get('coupling_strength', QValue(10, 'MHz'))
            g = coupling.number if isinstance(coupling, QValue) else 10
            self.lines.append(f"* Coupler {c.name}: {g}MHz")
            refs = []
            if isinstance(connects, QArray):
                refs = [str(i) for i in connects.items if isinstance(i, str)]
            if len(refs) >= 2 and refs[0] in qubit_nodes and refs[1] in qubit_nodes:
                cc = g / (2 * 5e9) * 1e15 * 1000
                self.lines.append(
                    f"CC_{c.name} {qubit_nodes[refs[0]]} {qubit_nodes[refs[1]]} {cc:.2f}fF"
                )
            self.lines.append("")

        self.lines.append(".ENDS QuantumChip")
        self.lines.append(".END")
        return '\n'.join(self.lines)


# ─── Main Compiler Entry ─────────────────────────────────────────────────────

def compile_qcl(prog: Program, target: str = 'qiskit_metal') -> str:
    """
    Compile a parsed+analyzed QChipLang AST to the specified target.

    Targets:
      'qiskit_metal' — Qiskit Metal Python script
      'json_ir'      — JSON intermediate representation
      'spice'        — SPICE netlist
    """
    if target == 'qiskit_metal':
        return QiskitMetalBackend(prog).generate()
    elif target == 'json_ir':
        return JSONIRBackend(prog).generate()
    elif target == 'spice':
        return SPICEBackend(prog).generate()
    else:
        raise CodegenError(f"Unknown target: {target}")
