"""Pure string generation for standalone Qiskit Metal designs."""
from __future__ import annotations

from app.core.editor_models import DesignDocument, GeneratedCode


class CodegenService:
    """Emit a self-contained Qiskit Metal Python script."""

    def generate(self, design: DesignDocument) -> GeneratedCode:
        """Generate code without importing Qiskit Metal in this call."""
        from app.services.component_registry import component_registry_service

        imports: set[str] = {"from qiskit_metal import designs"}
        setup = [
            "design = designs.DesignPlanar()",
            "design.overwrite_enabled = True",
            "",
        ]
        placement_lines = []
        route_lines = []
        placement_names = {placement.id: placement.name for placement in design.placements}

        for placement in design.placements:
            summary = component_registry_service.get_component(placement.componentId)
            if summary is None:
                placement_lines.append(
                    f"# WARNING: unknown component {placement.componentId!r} - skipped"
                )
                continue

            class_name = placement.componentId
            imports.add(f"from {summary.module} import {class_name}")
            options = {key: str(value) for key, value in placement.params.items()}
            options["pos_x"] = f"{placement.x}mm"
            options["pos_y"] = f"{placement.y}mm"
            if placement.rotation:
                options["orientation"] = str(placement.rotation)
            placement_lines.append(
                f"{placement.name} = {class_name}("
                f"design, {placement.name!r}, options={_fmt_opts(options)})"
            )

        for connection in design.connections:
            route_id = connection.routeComponentId or "RouteMeander"
            route_summary = component_registry_service.get_component(route_id)
            if route_summary is None:
                route_lines.append(
                    f"# WARNING: unknown route component {route_id!r} - skipped"
                )
                continue

            imports.add(f"from {route_summary.module} import {route_id}")
            short_id = connection.id[:8]
            route_options = dict(connection.routeOverrides)
            route_options_string = ", ".join(
                f"{key}={value!r}" for key, value in route_options.items()
            )
            source_name = placement_names.get(
                connection.from_.placementId,
                connection.from_.placementId,
            )
            target_name = placement_names.get(
                connection.to.placementId,
                connection.to.placementId,
            )
            route_lines.extend(
                [
                    f"route_{short_id} = {route_id}(design, 'route_{short_id}', options=dict(",
                    f"    pin_inputs=dict(",
                    f"        start_pin=dict(component={source_name!r}, pin={connection.from_.pinName!r}),",
                    f"        end_pin=dict(component={target_name!r}, pin={connection.to.pinName!r}),",
                    f"    ),",
                    *(
                        [f"    {route_options_string},"]
                        if route_options_string
                        else []
                    ),
                    f"))",
                ]
            )

        header = (
            "# ----------------------------------------------------------------\n"
            "# Generated by Silicofeller - https://silicofeller.io\n"
            "# Run: pip install qiskit-metal && python this_file.py\n"
            "# ----------------------------------------------------------------\n"
        )
        sorted_imports = "\n".join(sorted(imports))
        body = "\n".join(
            setup
            + placement_lines
            + [""]
            + route_lines
            + ["", "design.rebuild()", ""]
        )
        code = f"{header}\n{sorted_imports}\n\n{body}\n"
        return GeneratedCode(language="python", filename="design.py", code=code)


codegen_service = CodegenService()


def generate_from_editor_state(
    components: list,
    connections: list,
    variables: dict | None = None,
) -> dict:
    """
    Generate Qiskit Metal Python from a legacy editor-state payload.

    This is the single public entry point for the /generate/metal-code endpoint.
    Internally delegates to metal_codegen.MetalCodeGenerator so callers don't need
    to import from metal_codegen directly.

    Returns a dict with keys: code, warnings, component_count, filename.
    """
    from app.services.metal_codegen.adapter import editor_state_to_design
    from app.services.metal_codegen.metal_codegen import MetalCodeGenerator

    design = editor_state_to_design(
        components=components,
        connections=connections,
        variables=variables or {},
    )
    result = MetalCodeGenerator(design).generate()
    return {
        "code": result.source_code,
        "warnings": result.warnings or [],
        "component_count": result.component_count,
        "filename": "design.py",
    }


def _fmt_opts(options: dict) -> str:
    if not options:
        return "dict()"
    pairs = ", ".join(f"{key}={value!r}" for key, value in options.items())
    return f"dict({pairs})"
