"""Add persistent simulation database schema

Revision ID: 63c47c9468ce
Revises: 3a928ef18bc8
Create Date: 2026-06-25 11:55:32.592877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c47c9468ce'
down_revision: Union[str, None] = '3a928ef18bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('palace_version', sa.String(length=50), nullable=True),
    sa.Column('mpi_version', sa.String(length=50), nullable=True),
    sa.Column('configuration_checksum', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('geometry_metadata', sa.JSON(), nullable=True),
    sa.Column('mesh_metadata', sa.JSON(), nullable=True),
    sa.Column('config_metadata', sa.JSON(), nullable=True),
    sa.Column('runner_metadata', sa.JSON(), nullable=True),
    sa.Column('execution_summary', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_executions_simulation_id'), 'simulation_executions', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_simulation_executions_workspace_id'), 'simulation_executions', ['workspace_id'], unique=False)
    op.create_table('simulation_parameters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('parameter_key', sa.String(length=100), nullable=False),
    sa.Column('parameter_value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_parameters_parameter_key'), 'simulation_parameters', ['parameter_key'], unique=False)
    op.create_index(op.f('ix_simulation_parameters_simulation_id'), 'simulation_parameters', ['simulation_id'], unique=False)
    op.create_table('simulation_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('retention_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['simulation_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_artifacts_execution_id'), 'simulation_artifacts', ['execution_id'], unique=False)
    op.create_table('simulation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('log_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['simulation_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_logs_execution_id'), 'simulation_logs', ['execution_id'], unique=False)
    op.create_table('simulation_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['simulation_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_metrics_execution_id'), 'simulation_metrics', ['execution_id'], unique=False)
    op.create_index(op.f('ix_simulation_metrics_metric_key'), 'simulation_metrics', ['metric_key'], unique=False)
    op.create_table('simulation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('solver_type', sa.String(length=64), nullable=False),
    sa.Column('parsed_results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['simulation_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_results_execution_id'), 'simulation_results', ['execution_id'], unique=True)
    op.create_index(op.f('ix_simulation_results_simulation_id'), 'simulation_results', ['simulation_id'], unique=False)
    op.create_table('workspace_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['simulation_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_snapshots_execution_id'), 'workspace_snapshots', ['execution_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_snapshots_execution_id'), table_name='workspace_snapshots')
    op.drop_table('workspace_snapshots')
    op.drop_index(op.f('ix_simulation_results_simulation_id'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_execution_id'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index(op.f('ix_simulation_metrics_metric_key'), table_name='simulation_metrics')
    op.drop_index(op.f('ix_simulation_metrics_execution_id'), table_name='simulation_metrics')
    op.drop_table('simulation_metrics')
    op.drop_index(op.f('ix_simulation_logs_execution_id'), table_name='simulation_logs')
    op.drop_table('simulation_logs')
    op.drop_index(op.f('ix_simulation_artifacts_execution_id'), table_name='simulation_artifacts')
    op.drop_table('simulation_artifacts')
    op.drop_index(op.f('ix_simulation_parameters_simulation_id'), table_name='simulation_parameters')
    op.drop_index(op.f('ix_simulation_parameters_parameter_key'), table_name='simulation_parameters')
    op.drop_table('simulation_parameters')
    op.drop_index(op.f('ix_simulation_executions_workspace_id'), table_name='simulation_executions')
    op.drop_index(op.f('ix_simulation_executions_simulation_id'), table_name='simulation_executions')
    op.drop_table('simulation_executions')
    # ### end Alembic commands ###
