import React from "react";
import { AlertBox } from "../AlertBox";
import { CodeBlock } from "../CodeBlock";

export default function Section() {
  return (
    <>
      <div className="section-heading">
        <div>
          <p className="eyebrow">Core Technologies</p>
          <h2>Compiler Pipeline & Metal Generation</h2>
        </div>
      </div>
      <p>
        The Silicofeller Compiler is a state-of-the-art multi-stage engine that translates high-level QCLang definitions into physical, simulation-ready superconducting layouts and Qiskit Metal code. It is tightly integrated with the AI Copilot to provide real-time feedback.
      </p>

      <h3>End-to-End Core Workflow</h3>
      <div className="p-6 bg-[#1a1b26] text-[#a9b1d6] border border-[#24283b] rounded-xl font-mono text-sm mb-8 whitespace-pre overflow-x-auto shadow-lg">
{`[ AI Copilot ] -> "Generate 12-qubit heavy hex"
       ↓
QCLang Source Code
       ↓
[ Lexer & Parser ] -> Tokenization & Syntax Checking
       ↓
Abstract Syntax Tree (AST)
       ↓
[ Design Rule Checking (DRC) ] -> Spatial & Frequency Validation
       ↓ (If Failed: AI Copilot Auto-Fixes AST)
[ Intermediate Representation (IR) ]
       ↓
[ Synthesis Engine ] -> Topological Placement & Constraints
       ↓
[ Routing Engine ] -> CPW Meander & Feedline Routing
       ↓
Physical Layout Graph (JSON)
       ↓
[ Qiskit Metal Generator ] -> Converts Graph to Python Metal Code
       ↓
Final Outputs: [ Metal.py ] | [ GDSII ] | [ Simulation Ready ]`}
      </div>

      <h3>Stage 1: AI Generation & Parsing</h3>
      <p>The workflow begins either through manual coding or the <strong>QuantumChipGen AI Copilot</strong>. The compiler first tokenizes the QCLang source and builds an Abstract Syntax Tree (AST), understanding complex constraints like topology types and qubit-to-resonator couplings.</p>

      <h3>Stage 2: Design Rule Checking (DRC)</h3>
      <p>The Semantic Validator checks for architectural violations. This includes checking for frequency collisions, overlapping bounding boxes, and routing impossibility. If the DRC fails, the compiler passes the exact error stack back to the AI Copilot for automated resolution.</p>

      <h3>Stage 3: Synthesis & Routing</h3>
      <p>Once DRC passes, the AST is converted to an IR graph. The Synthesis engine places the components (Transmons, Feedlines, Pads) according to the specified topology, calculating the exact Euclidean coordinates. The Routing engine automatically draws the Coplanar Waveguides (CPW), calculating the necessary meanders to hit target resonant frequencies.</p>

      <h3>Stage 4: Qiskit Metal Code Generation</h3>
      <p>The final step of the compiler pipeline is the <strong>Export Engine</strong>. The engine takes the physical layout graph and transpiles it directly into IBM's Qiskit Metal Python API.</p>
      
      <CodeBlock language="python" code={`# Automatically Generated by Silicofeller Compiler
from qiskit_metal import designs, MetalGUI
from qiskit_metal.qlibrary.qubits.transmon_cross import TransmonCross

design = designs.DesignPlanar()
gui = MetalGUI(design)

# Qubit Q1 Synthesized Placement
q1 = TransmonCross(design, 'Q1', options=dict(
    pos_x='-1.5mm', pos_y='0.0mm',
    connection_pads=dict(
        readout=dict(connector_type='0', connector_location='90', trace_width='10um')
    )
))

gui.rebuild()
gui.autoscale()`} />

      <AlertBox type="tip" title="Seamless Simulation">
        Because the generated Metal code is fully parameterized, it can immediately be hooked into Qiskit Metal's Ansys (HFSS/Q3D) renderers for immediate physical simulation without any manual GUI drawing.
      </AlertBox>
    </>
  );
}
