import React from "react";
import { CodeBlock } from "../CodeBlock";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Qiskit Metal Integration</h1>
      <p className="text-lg text-slate-600 mb-8">
        Export an entire project directly as a functional Qiskit Metal Python script.
      </p>

      <CodeBlock language="python" code={`# Generated by Silicofeller Quantum Studio
import qiskit_metal as metal
from qiskit_metal import designs, draw

design = designs.DesignPlanar()
design.overwrite_enabled = True

# Custom Components
from qiskit_metal.qlibrary.qubits.transmon_cross import TransmonCross
# ... instantiation generated here ...

gui = metal.MetalGUI(design)
gui.rebuild()
gui.autoscale()`} />
    </div>
  );
}
