import React from "react";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Four-Domain DRC: Fabrication</h1>
      <p className="text-lg text-slate-600 mb-8">
        Fabrication DRC ensures that the geometric polygons generated by your layout can actually be manufactured using standard photolithography and e-beam processes at your target foundry.
      </p>

      <div className="my-8 rounded-xl overflow-hidden border border-slate-200 shadow-sm">
        <img src="/brain/63033335-280b-4630-beb9-8bb527edd274/validation_drc_1782265191432.png" alt="Fabrication Checks" className="w-full h-auto object-cover" />
      </div>

      <h2 className="text-2xl font-bold mb-4 mt-10">Lithography Constraints</h2>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-10">
        <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
          <h3 className="font-bold text-slate-900 mb-2">1. Minimum Trace Width</h3>
          <p className="text-sm text-slate-600">Standard 193nm DUV steppers cannot reliably print features smaller than 1µm. If you request a CPW trace width of 0.5µm, you are forcing the foundry to use slow, expensive E-beam lithography for the entire base layer. The engine flags traces below the photolithography limit.</p>
        </div>
        <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
          <h3 className="font-bold text-slate-900 mb-2">2. Acute Angle (Acid Trap)</h3>
          <p className="text-sm text-slate-600">Polygon vertices with internal angles &lt; 45° act as "acid traps" during wet etching, where chemical etchant pools and over-etches the surrounding metal. The DRC engine flags any acute angles in meandering resonators.</p>
        </div>
        <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
          <h3 className="font-bold text-slate-900 mb-2">3. Minimum Area</h3>
          <p className="text-sm text-slate-600">Tiny isolated islands of metal ("dust") can flake off during lift-off processes and short out adjacent structures. Polygons smaller than 2µm² are flagged.</p>
        </div>
        <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
          <h3 className="font-bold text-slate-900 mb-2">4. Chip Boundary Clearance</h3>
          <p className="text-sm text-slate-600">Features cannot be placed closer than 50µm to the dicing streets. The mechanical dicing saw causes micro-fractures that will destroy any nearby quantum coherence.</p>
        </div>
      </div>

      <AlertBox type="warning" title="Foundry Variability">
        Every foundry (e.g., MIT Lincoln Labs, Rigetti Foundry Services) has a unique rule deck. Ensure you select the correct Foundry Profile in your Project Settings so the Fabrication DRC applies the correct limitations.
      </AlertBox>
    </div>
  );
}