import React from "react";
import { CodeBlock } from "../CodeBlock";
import { AlertBox } from "../AlertBox";

export default function Section() {
  return (
    <div className="documentation-page-content max-w-4xl">
      <h1 className="text-4xl font-extrabold mb-6">Generated Qiskit Metal Code</h1>
      <p className="text-lg text-slate-600 mb-8">
        Silicofeller Quantum Studio is built on top of IBM's open-source Qiskit Metal framework. The entire visual schematic is backed by dynamically generated Python scripts.
      </p>

      <h2 className="text-2xl font-bold mb-4 mt-10">Exporting the Script</h2>
      <p className="text-slate-600 mb-6">
        You can export the entire project as a standalone Python file (.py) or a Jupyter Notebook (.ipynb). This script can be run locally on any machine with Qiskit Metal installed, completely independent of the Silicofeller cloud.
      </p>

      <CodeBlock language="python" code={`# Auto-generated by Silicofeller Quantum Studio
import qiskit_metal as metal
from qiskit_metal import designs, draw
from qiskit_metal.qlibrary.qubits.transmon_cross import TransmonCross

# 1. Initialize Design
design = designs.DesignPlanar()
design.overwrite_enabled = True

# 2. Setup Substrate
design.setup.drc.spacing_min = '5um'
design.setup.drc.trace_width = '10um'

# 3. Instantiate Components
Q1 = TransmonCross(design, 'Q1', options=dict(
    pos_x='0um', pos_y='0um',
    cross_width='30um', cross_length='200um',
    connection_pads=dict(
        readout=dict(connector_type='0', connector_location='90', trace_gap='4um')
    )
))

# 4. Rebuild UI
gui = metal.MetalGUI(design)
gui.rebuild()
gui.autoscale()
`} />

      <AlertBox type="info" title="No Vendor Lock-in">
        Because the output is pure Qiskit Metal, you are never locked into the Silicofeller ecosystem. You own the code and can modify it locally using any standard IDE.
      </AlertBox>
    </div>
  );
}