"""
formats.py — Individual export format generators.

All functions accept a DesignGraph and supporting dicts,
returning a string (text formats) or bytes (binary formats).
"""

from __future__ import annotations

import json
import math
from datetime import datetime
from typing import Any, Optional

from app.core.design_graph.graph import DesignGraph
from app.core.design_graph.serializer import graph_to_dict

# ── GDS-II layer map ──────────────────────────────────────────────────────────
LAYER_MAP = {
    "QUBIT":      1,
    "RESONATOR":  2,
    "COUPLER":    3,
    "FEEDLINE":   4,
    "GROUND":     5,
    "JUNCTION":   6,
    "PAD":        7,
    "DICING":     8,
}


# ─────────────────────────────────────────────────────────────────────────────
# JSON
# ─────────────────────────────────────────────────────────────────────────────

def export_json(
    graph: DesignGraph,
    freq_plan: dict[str, Any] | None = None,
    route_result: dict[str, Any] | None = None,
    drc_report: dict[str, Any] | None = None,
    constraints: dict[str, Any] | None = None,
) -> str:
    """Export complete design as a structured JSON string."""
    payload: dict[str, Any] = {
        "format":     "quantum_studio_design_v2",
        "generated":  datetime.utcnow().isoformat(),
        "design":     graph_to_dict(graph),
    }
    if freq_plan:
        payload["frequency_plan"] = freq_plan
    if route_result:
        payload["routing"] = route_result
    if drc_report:
        payload["drc"] = drc_report
    if constraints:
        payload["constraints"] = constraints
    return json.dumps(payload, indent=2)


# ─────────────────────────────────────────────────────────────────────────────
# QCLang source
# ─────────────────────────────────────────────────────────────────────────────

def export_qclang(graph: DesignGraph) -> str:
    """Export DesignGraph as QCLang .qc source file."""
    lines = [
        f"# Auto-generated by Quantum Studio V2 — {datetime.utcnow().strftime('%Y-%m-%d %H:%M')}",
        f"chip {graph.chip_name}",
        "",
        f"  variable chip_width  = {graph.chip_width_mm}",
        f"  variable chip_height = {graph.chip_height_mm}",
        f'  variable substrate   = "{graph.substrate}"',
        f'  variable metal       = "{graph.metal}"',
        "",
    ]

    for q in sorted(graph.qubits, key=lambda x: x.id):
        lines.append(
            f"  qubit {q.id} type={q.qubit_type.value} "
            f"frequency={q.frequency_ghz:.4f}"
        )

    lines.append("")
    ci = 1
    for c in sorted(graph.couplers, key=lambda x: x.id):
        if c.qubit_a_id and c.qubit_b_id:
            lines.append(
                f"  coupler C{ci} connect({c.qubit_a_id},{c.qubit_b_id})"
            )
            ci += 1

    lines.append("")
    for r in sorted(graph.resonators, key=lambda x: x.id):
        if r.target_qubit_id:
            lines.append(f"  readout {r.id} connect({r.target_qubit_id})")

    lines.append("")
    lines.append("end")
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# GDS-II ASCII
# ─────────────────────────────────────────────────────────────────────────────

def export_gds_ascii(
    graph: DesignGraph,
    project_name: str = "QuantumChip",
    version: str = "v1.0",
) -> str:
    """Generate ASCII GDS-II representation."""
    lines = [
        "HEADER 600",
        "BGNLIB",
        f"LIBNAME {project_name}_{version}.DB",
        "UNITS 0.001 1e-09",  # 1 unit = 1 nm
        "",
        "BGNSTR",
        f"STRNAME {project_name}_TOP",
        "",
        "# Ground plane",
        "BOUNDARY",
        f"LAYER {LAYER_MAP['GROUND']}",
        "DATATYPE 0",
        "XY 0 0 10000 0 10000 10000 0 10000 0 0",
        "ENDEL",
        "",
        "# Qubit pockets",
    ]

    for q in graph.qubits:
        if not q.placed:
            continue
        x = int((q.x_mm or 0) * 1000)
        y = int((q.y_mm or 0) * 1000)
        h = 330   # 330 nm = 0.33 mm half-size in nm units
        lines += [
            f"# {q.id} @ ({q.x_mm:.3f}, {q.y_mm:.3f}) mm",
            "BOUNDARY",
            f"LAYER {LAYER_MAP['QUBIT']}",
            "DATATYPE 0",
            f"XY {x-h} {y-h} {x+h} {y-h} {x+h} {y+h} {x-h} {y+h} {x-h} {y-h}",
            "ENDEL",
            "",
            "# Josephson Junction",
            "BOUNDARY",
            f"LAYER {LAYER_MAP['JUNCTION']}",
            "DATATYPE 0",
            f"XY {x-20} {y-20} {x+20} {y-20} {x+20} {y+20} {x-20} {y+20} {x-20} {y-20}",
            "ENDEL",
            "",
        ]

    lines += ["ENDSTR", "", "ENDLIB"]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# SVG
# ─────────────────────────────────────────────────────────────────────────────

def export_svg(
    graph: DesignGraph,
    width_px: int = 800,
    height_px: int = 800,
) -> str:
    """Generate SVG chip layout diagram."""
    qubits = [q for q in graph.qubits if q.placed]
    couplers = graph.couplers

    if not qubits:
        return '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="800"><text x="400" y="400" text-anchor="middle">No placed qubits</text></svg>'

    # Compute bounding box
    xs = [q.x_mm for q in qubits]
    ys = [q.y_mm for q in qubits]
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)
    pad = max(graph.chip_width_mm * 0.1, 0.5)

    def to_px(x_mm: float, y_mm: float):
        rx = (x_mm - min_x + pad) / (max_x - min_x + 2 * pad) * width_px
        ry = (1.0 - (y_mm - min_y + pad) / (max_y - min_y + 2 * pad)) * height_px
        return round(rx, 1), round(ry, 1)

    r_px = max(12, int(width_px / max(len(qubits) * 3, 10)))
    qubit_map = {q.id: to_px(q.x_mm, q.y_mm) for q in qubits}

    svg = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width_px}" height="{height_px}" '
        f'style="background:#0F172A">',
        f'  <rect x="0" y="0" width="{width_px}" height="{height_px}" fill="#0F172A"/>',
        '  <!-- Chip boundary -->',
        f'  <rect x="20" y="20" width="{width_px-40}" height="{height_px-40}" '
        f'fill="none" stroke="#334155" stroke-width="2" stroke-dasharray="8,4"/>',
    ]

    # Coupler lines
    svg.append('  <!-- Couplers -->')
    for c in couplers:
        pa = qubit_map.get(c.qubit_a_id)
        pb = qubit_map.get(c.qubit_b_id)
        if pa and pb:
            svg.append(
                f'  <line x1="{pa[0]}" y1="{pa[1]}" x2="{pb[0]}" y2="{pb[1]}" '
                f'stroke="#F59E0B" stroke-width="2" opacity="0.7"/>'
            )

    # Resonator stubs
    svg.append('  <!-- Resonators -->')
    for res in graph.resonators:
        if not res.target_qubit_id:
            continue
        pa = qubit_map.get(res.target_qubit_id)
        if pa:
            # Draw a small meander symbol above the qubit
            x0, y0 = pa
            svg.append(
                f'  <polyline points="{x0},{y0-r_px} {x0-8},{y0-r_px-10} '
                f'{x0+8},{y0-r_px-18} {x0-8},{y0-r_px-26} {x0+8},{y0-r_px-34}" '
                f'fill="none" stroke="#60A5FA" stroke-width="1.5"/>'
            )

    # Qubits
    svg.append('  <!-- Qubits -->')
    for q in qubits:
        px, py = qubit_map[q.id]
        svg += [
            f'  <rect x="{px-r_px}" y="{py-r_px}" width="{r_px*2}" height="{r_px*2}" '
            f'rx="3" fill="#1E293B" stroke="#7C3AED" stroke-width="2"/>',
            f'  <line x1="{px-r_px+4}" y1="{py}" x2="{px+r_px-4}" y2="{py}" '
            f'stroke="#D97706" stroke-width="3"/>',
            f'  <line x1="{px}" y1="{py-4}" x2="{px}" y2="{py+4}" '
            f'stroke="#EF4444" stroke-width="2"/>',
            f'  <text x="{px}" y="{py+r_px+14}" text-anchor="middle" '
            f'font-size="10" font-family="monospace" fill="#94A3B8">{q.id}</text>',
        ]

    svg.append('</svg>')
    return "\n".join(svg)


# ─────────────────────────────────────────────────────────────────────────────
# DXF (minimal 2D AutoCAD compatible)
# ─────────────────────────────────────────────────────────────────────────────

def export_dxf(graph: DesignGraph) -> str:
    """Generate a minimal DXF R12 file with qubit pocket outlines."""
    lines = [
        "0\nSECTION", "2\nHEADER",
        "9\n$ACADVER", "1\nAC1009",
        "0\nENDSEC",
        "0\nSECTION", "2\nENTITIES",
    ]

    for q in graph.qubits:
        if not q.placed:
            continue
        x, y = q.x_mm or 0.0, q.y_mm or 0.0
        h = 0.33  # half pocket size mm
        # LWPOLYLINE as 4 points
        corners = [
            (x - h, y - h), (x + h, y - h),
            (x + h, y + h), (x - h, y + h),
        ]
        lines += [
            "0\nLWPOLYLINE",
            "8\nQUBIT",     # layer
            "90\n4",        # 4 vertices
            "70\n1",        # closed
        ]
        for cx, cy in corners:
            lines += [f"10\n{cx:.4f}", f"20\n{cy:.4f}"]

    lines += ["0\nENDSEC", "0\nEOF"]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# PDF report (text-based — real PDF requires reportlab)
# ─────────────────────────────────────────────────────────────────────────────

def export_pdf_report(
    graph: DesignGraph,
    freq_plan: dict[str, Any] | None = None,
    drc_report: dict[str, Any] | None = None,
    constraints: dict[str, Any] | None = None,
    project_name: str = "QuantumChip",
    version: str = "v1.0",
) -> str:
    """
    Generate a human-readable design report (plain text, PDF-ready).
    Real PDF rendering requires reportlab — this returns a formatted text report.
    """
    sep = "─" * 70
    lines = [
        sep,
        f"  QUANTUM STUDIO V2 — DESIGN REPORT",
        f"  {project_name} · {version}",
        f"  Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        sep, "",
        "  DESIGN SUMMARY",
        sep,
        f"  Chip Name   : {graph.chip_name}",
        f"  Chip Size   : {graph.chip_width_mm} × {graph.chip_height_mm} mm",
        f"  Substrate   : {graph.substrate}",
        f"  Metal       : {graph.metal}",
        f"  Topology    : {graph.topology}",
        f"  Qubits      : {len(graph.qubits)}",
        f"  Couplers    : {len(graph.couplers)}",
        f"  Resonators  : {len(graph.resonators)}",
        f"  Feedlines   : {len(graph.feedlines)}",
        "",
    ]

    if freq_plan:
        lines += [
            "  FREQUENCY PLAN",
            sep,
            f"  ε_eff       : {freq_plan.get('epsilon_eff', '—')}",
            "",
            f"  {'Qubit':<10} {'Group':<7} {'f_01 (GHz)':<14} {'EJ (GHz)':<12} {'EC (GHz)':<10}",
            f"  {'─'*10} {'─'*7} {'─'*14} {'─'*12} {'─'*10}",
        ]
        qfreqs  = freq_plan.get("qubit_frequencies_GHz", {})
        groups  = freq_plan.get("qubit_groups", {})
        ej_map  = freq_plan.get("EJ_GHz", {})
        ec_map  = freq_plan.get("EC_GHz", {})
        for name in sorted(qfreqs):
            lines.append(
                f"  {name:<10} {str(groups.get(name,'')):<7} "
                f"{qfreqs[name]:<14.4f} {ej_map.get(name,0):<12.2f} {ec_map.get(name,0):<10.4f}"
            )
        lines.append("")

        rfreqs  = freq_plan.get("resonator_frequencies_GHz", {})
        rlens   = freq_plan.get("resonator_lengths_mm", {})
        dets    = freq_plan.get("detunings_GHz", {})
        if rfreqs:
            lines += [
                f"  {'Resonator':<12} {'f_r (GHz)':<14} {'Δ (GHz)':<12} {'L mm':<10}",
                f"  {'─'*12} {'─'*14} {'─'*12} {'─'*10}",
            ]
            for name in sorted(rfreqs):
                lines.append(
                    f"  {name:<12} {rfreqs[name]:<14.4f} "
                    f"{dets.get(name,0):<12.4f} {rlens.get(name,0):<10.4f}"
                )
            lines.append("")

    if drc_report:
        passed = drc_report.get("passed", True)
        lines += [
            "  DRC REPORT",
            sep,
            f"  Status  : {'✓ PASSED' if passed else '✗ FAILED'}",
            f"  Errors  : {drc_report.get('errors', 0)}",
            f"  Warnings: {drc_report.get('warnings', 0)}",
            "",
        ]
        for v in drc_report.get("violations", []):
            lines.append(
                f"  [{v.get('severity','?')}] {v.get('domain','').upper()}.{v.get('rule','')}: "
                f"{v.get('message','')}"
            )
        lines.append("")

    lines += [sep, "  END OF REPORT", sep]
    return "\n".join(lines)
