/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentationIndexRouteImport } from './routes/documentation/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppVersionControlRouteImport } from './routes/_app/version-control'
import { Route as AppVerificationRouteImport } from './routes/_app/verification'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSimulationsRouteImport } from './routes/_app/simulations'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSchematicEditorRouteImport } from './routes/_app/schematic-editor'
import { Route as AppResultsRouteImport } from './routes/_app/results'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPhysicsAnalysisRouteImport } from './routes/_app/physics-analysis'
import { Route as AppLayoutViewerRouteImport } from './routes/_app/layout-viewer'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppFaultToleranceRouteImport } from './routes/_app/fault-tolerance'
import { Route as AppDesignerRouteImport } from './routes/_app/designer'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppComponentLibraryRouteImport } from './routes/_app/component-library'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppArchitectureExplorerRouteImport } from './routes/_app/architecture-explorer'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAboutRouteImport } from './routes/_app/about'

const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationIndexRoute = DocumentationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentationRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppVersionControlRoute = AppVersionControlRouteImport.update({
  id: '/version-control',
  path: '/version-control',
  getParentRoute: () => AppRoute,
} as any)
const AppVerificationRoute = AppVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulationsRoute = AppSimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSchematicEditorRoute = AppSchematicEditorRouteImport.update({
  id: '/schematic-editor',
  path: '/schematic-editor',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPhysicsAnalysisRoute = AppPhysicsAnalysisRouteImport.update({
  id: '/physics-analysis',
  path: '/physics-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppLayoutViewerRoute = AppLayoutViewerRouteImport.update({
  id: '/layout-viewer',
  path: '/layout-viewer',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppFaultToleranceRoute = AppFaultToleranceRouteImport.update({
  id: '/fault-tolerance',
  path: '/fault-tolerance',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignerRoute = AppDesignerRouteImport.update({
  id: '/designer',
  path: '/designer',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComponentLibraryRoute = AppComponentLibraryRouteImport.update({
  id: '/component-library',
  path: '/component-library',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppArchitectureExplorerRoute = AppArchitectureExplorerRouteImport.update({
  id: '/architecture-explorer',
  path: '/architecture-explorer',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/community': typeof CommunityRoute
  '/documentation': typeof DocumentationRouteWithChildren
  '/about': typeof AppAboutRoute
  '/admin': typeof AppAdminRoute
  '/architecture-explorer': typeof AppArchitectureExplorerRoute
  '/billing': typeof AppBillingRoute
  '/component-library': typeof AppComponentLibraryRoute
  '/dashboard': typeof AppDashboardRoute
  '/designer': typeof AppDesignerRoute
  '/fault-tolerance': typeof AppFaultToleranceRoute
  '/integrations': typeof AppIntegrationsRoute
  '/layout-viewer': typeof AppLayoutViewerRoute
  '/physics-analysis': typeof AppPhysicsAnalysisRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/schematic-editor': typeof AppSchematicEditorRoute
  '/settings': typeof AppSettingsRoute
  '/simulations': typeof AppSimulationsRoute
  '/team': typeof AppTeamRoute
  '/verification': typeof AppVerificationRoute
  '/version-control': typeof AppVersionControlRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/documentation/': typeof DocumentationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/about': typeof AppAboutRoute
  '/admin': typeof AppAdminRoute
  '/architecture-explorer': typeof AppArchitectureExplorerRoute
  '/billing': typeof AppBillingRoute
  '/component-library': typeof AppComponentLibraryRoute
  '/dashboard': typeof AppDashboardRoute
  '/designer': typeof AppDesignerRoute
  '/fault-tolerance': typeof AppFaultToleranceRoute
  '/integrations': typeof AppIntegrationsRoute
  '/layout-viewer': typeof AppLayoutViewerRoute
  '/physics-analysis': typeof AppPhysicsAnalysisRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/schematic-editor': typeof AppSchematicEditorRoute
  '/settings': typeof AppSettingsRoute
  '/simulations': typeof AppSimulationsRoute
  '/team': typeof AppTeamRoute
  '/verification': typeof AppVerificationRoute
  '/version-control': typeof AppVersionControlRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/documentation': typeof DocumentationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/community': typeof CommunityRoute
  '/documentation': typeof DocumentationRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/architecture-explorer': typeof AppArchitectureExplorerRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/component-library': typeof AppComponentLibraryRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/designer': typeof AppDesignerRoute
  '/_app/fault-tolerance': typeof AppFaultToleranceRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/layout-viewer': typeof AppLayoutViewerRoute
  '/_app/physics-analysis': typeof AppPhysicsAnalysisRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/schematic-editor': typeof AppSchematicEditorRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/simulations': typeof AppSimulationsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/verification': typeof AppVerificationRoute
  '/_app/version-control': typeof AppVersionControlRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/documentation/': typeof DocumentationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/community'
    | '/documentation'
    | '/about'
    | '/admin'
    | '/architecture-explorer'
    | '/billing'
    | '/component-library'
    | '/dashboard'
    | '/designer'
    | '/fault-tolerance'
    | '/integrations'
    | '/layout-viewer'
    | '/physics-analysis'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/results'
    | '/schematic-editor'
    | '/settings'
    | '/simulations'
    | '/team'
    | '/verification'
    | '/version-control'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/blog/$slug'
    | '/blog/'
    | '/documentation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/about'
    | '/admin'
    | '/architecture-explorer'
    | '/billing'
    | '/component-library'
    | '/dashboard'
    | '/designer'
    | '/fault-tolerance'
    | '/integrations'
    | '/layout-viewer'
    | '/physics-analysis'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/results'
    | '/schematic-editor'
    | '/settings'
    | '/simulations'
    | '/team'
    | '/verification'
    | '/version-control'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/blog/$slug'
    | '/blog'
    | '/documentation'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/blog'
    | '/community'
    | '/documentation'
    | '/_app/about'
    | '/_app/admin'
    | '/_app/architecture-explorer'
    | '/_app/billing'
    | '/_app/component-library'
    | '/_app/dashboard'
    | '/_app/designer'
    | '/_app/fault-tolerance'
    | '/_app/integrations'
    | '/_app/layout-viewer'
    | '/_app/physics-analysis'
    | '/_app/profile'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/results'
    | '/_app/schematic-editor'
    | '/_app/settings'
    | '/_app/simulations'
    | '/_app/team'
    | '/_app/verification'
    | '/_app/version-control'
    | '/_auth/forgot-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/blog/$slug'
    | '/blog/'
    | '/documentation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  DocumentationRoute: typeof DocumentationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/': {
      id: '/documentation/'
      path: '/'
      fullPath: '/documentation/'
      preLoaderRoute: typeof DocumentationIndexRouteImport
      parentRoute: typeof DocumentationRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/version-control': {
      id: '/_app/version-control'
      path: '/version-control'
      fullPath: '/version-control'
      preLoaderRoute: typeof AppVersionControlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verification': {
      id: '/_app/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AppVerificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/simulations': {
      id: '/_app/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof AppSimulationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schematic-editor': {
      id: '/_app/schematic-editor'
      path: '/schematic-editor'
      fullPath: '/schematic-editor'
      preLoaderRoute: typeof AppSchematicEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/physics-analysis': {
      id: '/_app/physics-analysis'
      path: '/physics-analysis'
      fullPath: '/physics-analysis'
      preLoaderRoute: typeof AppPhysicsAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/layout-viewer': {
      id: '/_app/layout-viewer'
      path: '/layout-viewer'
      fullPath: '/layout-viewer'
      preLoaderRoute: typeof AppLayoutViewerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fault-tolerance': {
      id: '/_app/fault-tolerance'
      path: '/fault-tolerance'
      fullPath: '/fault-tolerance'
      preLoaderRoute: typeof AppFaultToleranceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/designer': {
      id: '/_app/designer'
      path: '/designer'
      fullPath: '/designer'
      preLoaderRoute: typeof AppDesignerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/component-library': {
      id: '/_app/component-library'
      path: '/component-library'
      fullPath: '/component-library'
      preLoaderRoute: typeof AppComponentLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/architecture-explorer': {
      id: '/_app/architecture-explorer'
      path: '/architecture-explorer'
      fullPath: '/architecture-explorer'
      preLoaderRoute: typeof AppArchitectureExplorerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAdminRoute: typeof AppAdminRoute
  AppArchitectureExplorerRoute: typeof AppArchitectureExplorerRoute
  AppBillingRoute: typeof AppBillingRoute
  AppComponentLibraryRoute: typeof AppComponentLibraryRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDesignerRoute: typeof AppDesignerRoute
  AppFaultToleranceRoute: typeof AppFaultToleranceRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppLayoutViewerRoute: typeof AppLayoutViewerRoute
  AppPhysicsAnalysisRoute: typeof AppPhysicsAnalysisRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSchematicEditorRoute: typeof AppSchematicEditorRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSimulationsRoute: typeof AppSimulationsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppVerificationRoute: typeof AppVerificationRoute
  AppVersionControlRoute: typeof AppVersionControlRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAdminRoute: AppAdminRoute,
  AppArchitectureExplorerRoute: AppArchitectureExplorerRoute,
  AppBillingRoute: AppBillingRoute,
  AppComponentLibraryRoute: AppComponentLibraryRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDesignerRoute: AppDesignerRoute,
  AppFaultToleranceRoute: AppFaultToleranceRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppLayoutViewerRoute: AppLayoutViewerRoute,
  AppPhysicsAnalysisRoute: AppPhysicsAnalysisRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppReportsRoute: AppReportsRoute,
  AppResultsRoute: AppResultsRoute,
  AppSchematicEditorRoute: AppSchematicEditorRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSimulationsRoute: AppSimulationsRoute,
  AppTeamRoute: AppTeamRoute,
  AppVerificationRoute: AppVerificationRoute,
  AppVersionControlRoute: AppVersionControlRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DocumentationRouteChildren {
  DocumentationIndexRoute: typeof DocumentationIndexRoute
}

const DocumentationRouteChildren: DocumentationRouteChildren = {
  DocumentationIndexRoute: DocumentationIndexRoute,
}

const DocumentationRouteWithChildren = DocumentationRoute._addFileChildren(
  DocumentationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CommunityRoute: CommunityRoute,
  DocumentationRoute: DocumentationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
