import os
import re
import json

def parse_html_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        html = f.read()

    # Extract Category Tag
    cat_match = re.search(r'<span class="category-tag">(.*?)</span>', html, re.DOTALL)
    tag = cat_match.group(1).strip() if cat_match else "Quantum"

    # Extract Title
    title_match = re.search(r'<h1>(.*?)</h1>', html, re.DOTALL)
    title = title_match.group(1).strip() if title_match else "Untitled Post"
    title = re.sub(r'\s+', ' ', title) # clean whitespace

    # Extract Authors Names
    authors_match = re.search(r'<div class="author-names">(.*?)</div>', html, re.DOTALL)
    authors = authors_match.group(1).strip() if authors_match else ""

    # Extract Publish Date / Meta
    publish_match = re.search(r'<div class="publish-date">(.*?)</div>', html, re.DOTALL)
    publish_meta = publish_match.group(1).strip() if publish_match else ""

    # Extract Content Body
    content_match = re.search(r'<article class="content-body">(.*?)</article>', html, re.DOTALL)
    content_html = content_match.group(1).strip() if content_match else ""

    # Extract Author Section
    author_section_match = re.search(r'<section class="author-card-section">(.*?)</section>', html, re.DOTALL)
    author_html = author_section_match.group(1).strip() if author_section_match else ""

    # Extract Discussion/Comments Section (if exists)
    comments_match = re.search(r'<section class="discussion-section">(.*?)</section>', html, re.DOTALL)
    comments_html = comments_match.group(1).strip() if comments_match else ""

    # Replace relative image paths with absolute ones (e.g. ../images/ -> /images/)
    content_html = content_html.replace('../images/', '/images/')
    author_html = author_html.replace('../images/', '/images/')
    comments_html = comments_html.replace('../images/', '/images/')

    # Generate an excerpt from the content
    # Remove HTML tags to get plain text
    plain_text = re.sub(r'<[^>]+>', '', content_html)
    plain_text = re.sub(r'\s+', ' ', plain_text).strip()
    excerpt = plain_text[:160] + "..." if len(plain_text) > 160 else plain_text

    # Match nice dates for display
    # (Extract standard MM/YYYY or Month YYYY from publish_meta)
    date = "2025"
    date_patterns = [
        r'(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2},\s+\d{4}',
        r'(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{4}',
        r'\b\d{4}\b'
    ]
    for pattern in date_patterns:
        m = re.search(pattern, publish_meta)
        if m:
            date = m.group(0)
            break

    return {
        "tag": tag,
        "title": title,
        "authors": authors,
        "publishMeta": publish_meta,
        "contentHtml": content_html,
        "authorHtml": author_html,
        "commentsHtml": comments_html,
        "excerpt": excerpt,
        "date": date
    }

def main():
    blog_dir = r"s:\verify\Qubit-Pro\blog\blog_posts_and_images"
    posts_data = []

    # Hardcoded mapping of file names to tags and slugs
    files_to_parse = [
        {"path": "Research/shadow_hamiltonian.html", "slug": "shadow-hamiltonian-simulation"},
        {"path": "Quantum/surface_codes.html", "slug": "surface-codes-qec-architecture"},
        {"path": "Engineering/squadds_qubit_design.html", "slug": "squadds-qubit-design"},
        {"path": "Industry/cudaq_qec_decoders.html", "slug": "cudaq-qec-decoders"},
        {"path": "Industry/quantum_supremacy.html", "slug": "quantum-supremacy"}
    ]

    for item in files_to_parse:
        full_path = os.path.join(blog_dir, item["path"].replace("/", os.sep))
        print(f"Parsing: {full_path}")
        parsed = parse_html_file(full_path)
        parsed["slug"] = item["slug"]
        posts_data.append(parsed)

    # Output to TypeScript file
    out_dir = r"s:\verify\Qubit-Pro\frontend\src\data"
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "blog-posts.ts")

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("/* Auto-generated by parse_blogs.py. Do not edit manually. */\n\n")
        f.write("export interface BlogPost {\n")
        f.write("  slug: string;\n")
        f.write("  tag: string;\n")
        f.write("  title: string;\n")
        f.write("  excerpt: string;\n")
        f.write("  date: string;\n")
        f.write("  authors: string;\n")
        f.write("  publishMeta: string;\n")
        f.write("  contentHtml: string;\n")
        f.write("  authorHtml: string;\n")
        f.write("  commentsHtml?: string;\n")
        f.write("}\n\n")
        f.write("export const BLOG_POSTS: BlogPost[] = ")
        f.write(json.dumps(posts_data, indent=2, ensure_ascii=False))
        f.write(";\n")

    print(f"Successfully generated: {out_path}")

if __name__ == "__main__":
    main()
